/**
 * Vorgenerierte Kreuzworträtsel-Gitter -- erzeugt von scripts/generate-crosswords.js
 * aus scripts/crossword-wordbank.js. Nicht von Hand bearbeiten; bei Bedarf
 * das Skript erneut laufen lassen (überschreibt diese Datei komplett).
 *
 * Auswahl pro Runde läuft wie beim Wissens-Quiz über pickUnseen() (siehe
 * content/crossword.ts) -- kein Wiederholen, solange der Pool nicht
 * ausgeschöpft ist, kontogebunden bzw. geräte-lokal für Gäste.
 */

export interface CrosswordEntry {
  number: number;
  dir: "across" | "down";
  row: number;
  col: number;
  answer: string;
  clue: string;
}

export interface CrosswordPuzzle {
  id: string;
  rows: number;
  cols: number;
  /** null = schwarze/leere Zelle, sonst der Buchstabe an dieser Stelle. */
  grid: (string | null)[][];
  entries: CrosswordEntry[];
}

export const crosswordPuzzles: CrosswordPuzzle[] = [
  {
    id: "cw-01",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, "S", null, null, null, "Z", null],
      [null, null, null, null, null, null, "F", "A", "H", "R", "R", "A", "D"],
      ["F", null, null, null, null, null, null, "L", null, null, null, "U", null],
      ["U", null, null, null, null, null, null, "A", null, "F", null, "B", null],
      ["C", null, null, null, null, "I", "N", "T", "E", "R", "N", "E", "T"],
      ["H", null, null, null, null, null, null, null, null, "U", null, "R", null],
      ["S", "C", "H", "O", "K", "O", "L", "A", "D", "E", null, "E", null],
      [null, null, null, null, null, null, null, null, null, "H", null, "R", null],
      [null, "K", "A", "R", "T", "O", "F", "F", "E", "L", null, null, null],
      [null, null, null, null, null, null, null, null, null, "I", null, null, null],
      [null, "S", "C", "H", "W", "I", "M", "M", "E", "N", null, null, null],
      [null, "E", null, null, null, null, null, null, null, "G", null, null, null],
      [null, "E", "I", "S", null, null, null, null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 7, answer: "SALAT", clue: "Grünes, frisches Gericht" },
      { number: 2, dir: "down", row: 0, col: 11, answer: "ZAUBERER", clue: "Wirkt in Märchen mit Magie" },
      { number: 3, dir: "across", row: 1, col: 6, answer: "FAHRRAD", clue: "Zweirädriges Fahrzeug ohne Motor" },
      { number: 4, dir: "down", row: 2, col: 0, answer: "FUCHS", clue: "Schlaues, rotes Waldtier" },
      { number: 5, dir: "down", row: 3, col: 9, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 6, dir: "across", row: 4, col: 5, answer: "INTERNET", clue: "Weltweites Datennetz" },
      { number: 7, dir: "across", row: 6, col: 0, answer: "SCHOKOLADE", clue: "Süße Nascherei aus Kakao" },
      { number: 8, dir: "across", row: 8, col: 1, answer: "KARTOFFEL", clue: "Knolle, wird gekocht oder frittiert" },
      { number: 9, dir: "across", row: 10, col: 1, answer: "SCHWIMMEN", clue: "Sportliche Fortbewegung im Wasser" },
      { number: 9, dir: "down", row: 10, col: 1, answer: "SEE", clue: "Stehendes Binnengewässer" },
      { number: 10, dir: "across", row: 12, col: 1, answer: "EIS", clue: "Gefrorenes Wasser" },
    ],
  },
  {
    id: "cw-02",
    rows: 13,
    cols: 13,
    grid: [
      [null, "K", null, null, null, "S", null, null, "H", "A", "I", null, "D"],
      [null, "A", null, "B", null, "C", null, null, null, "P", null, null, "O"],
      [null, "R", null, "I", null, "H", null, "B", "R", "O", "T", null, "N"],
      [null, "T", null, "L", null, "O", null, null, null, "T", null, null, "N"],
      [null, "O", null, "D", null, "K", null, "S", "C", "H", "N", "E", "E"],
      [null, "F", null, "S", null, "O", null, null, null, "E", null, null, "R"],
      [null, "F", null, "C", null, "L", null, null, null, "K", null, null, null],
      ["W", "E", "I", "H", "N", "A", "C", "H", "T", "E", "N", null, null],
      [null, "L", null, "I", null, "D", null, null, null, null, null, null, null],
      [null, null, "F", "R", "U", "E", "H", "L", "I", "N", "G", null, null],
      [null, null, null, "M", null, null, "U", null, null, null, null, null, null],
      [null, null, null, null, null, null, "H", "U", "N", "D", null, null, null],
      [null, null, null, null, null, null, "N", null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 1, answer: "KARTOFFEL", clue: "Knolle, wird gekocht oder frittiert" },
      { number: 2, dir: "down", row: 0, col: 5, answer: "SCHOKOLADE", clue: "Süße Nascherei aus Kakao" },
      { number: 3, dir: "across", row: 0, col: 8, answer: "HAI", clue: "Gefürchteter Meeresräuber mit vielen Zähnen" },
      { number: 4, dir: "down", row: 0, col: 9, answer: "APOTHEKE", clue: "Verkauft Medikamente" },
      { number: 5, dir: "down", row: 0, col: 12, answer: "DONNER", clue: "Grollt nach dem Blitz" },
      { number: 6, dir: "down", row: 1, col: 3, answer: "BILDSCHIRM", clue: "Zeigt Inhalte am Computer an" },
      { number: 7, dir: "across", row: 2, col: 7, answer: "BROT", clue: "Wird aus Mehl gebacken" },
      { number: 8, dir: "across", row: 4, col: 7, answer: "SCHNEE", clue: "Weiße Winterflocken" },
      { number: 9, dir: "across", row: 7, col: 0, answer: "WEIHNACHTEN", clue: "Fest im Dezember mit Geschenken" },
      { number: 10, dir: "across", row: 9, col: 2, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 11, dir: "down", row: 9, col: 6, answer: "HUHN", clue: "Legt Eier im Stall" },
      { number: 12, dir: "across", row: 11, col: 6, answer: "HUND", clue: "Bester Freund des Menschen" },
    ],
  },
  {
    id: "cw-03",
    rows: 13,
    cols: 13,
    grid: [
      ["M", null, null, null, null, null, null, null, null, "S", null, null, null],
      ["E", null, "K", "N", "O", "B", "L", "A", "U", "C", "H", null, null],
      ["D", null, "A", null, null, null, null, null, null, "H", null, null, null],
      ["A", null, "R", null, null, null, null, null, "S", "A", "L", "Z", null],
      ["I", "N", "T", "E", "R", "N", "E", "T", null, "F", null, null, "S"],
      ["L", null, "O", null, null, null, null, null, "A", null, null, null, "T"],
      ["L", null, "F", null, null, "C", "O", "M", "P", "U", "T", "E", "R"],
      ["E", null, "F", null, null, null, null, null, "O", null, null, null, "A"],
      [null, "G", "E", "B", "U", "R", "T", "S", "T", "A", "G", null, "S"],
      [null, null, "L", null, null, null, null, null, "H", null, null, null, "S"],
      [null, null, null, "R", "O", "B", "O", "T", "E", "R", null, null, "E"],
      [null, null, null, null, null, null, null, null, "K", null, null, null, null],
      [null, null, "K", "A", "L", "E", "N", "D", "E", "R", null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 0, answer: "MEDAILLE", clue: "Auszeichnung für Sportler:innen" },
      { number: 2, dir: "down", row: 0, col: 9, answer: "SCHAF", clue: "Wolliges Weidetier" },
      { number: 3, dir: "across", row: 1, col: 2, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 3, dir: "down", row: 1, col: 2, answer: "KARTOFFEL", clue: "Knolle, wird gekocht oder frittiert" },
      { number: 4, dir: "across", row: 3, col: 8, answer: "SALZ", clue: "Würzt fast jedes Gericht" },
      { number: 5, dir: "across", row: 4, col: 0, answer: "INTERNET", clue: "Weltweites Datennetz" },
      { number: 6, dir: "down", row: 4, col: 12, answer: "STRASSE", clue: "Für Autos und Fußgänger gebaut" },
      { number: 7, dir: "down", row: 5, col: 8, answer: "APOTHEKE", clue: "Verkauft Medikamente" },
      { number: 8, dir: "across", row: 6, col: 5, answer: "COMPUTER", clue: "Elektronisches Rechengerät" },
      { number: 9, dir: "across", row: 8, col: 1, answer: "GEBURTSTAG", clue: "Jährlicher Feiertag der eigenen Geburt" },
      { number: 10, dir: "across", row: 10, col: 3, answer: "ROBOTER", clue: "Maschine, die menschliche Arbeit übernimmt" },
      { number: 11, dir: "across", row: 12, col: 2, answer: "KALENDER", clue: "Zeigt Tage und Monate an" },
    ],
  },
  {
    id: "cw-04",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, "S", "T", "R", "A", "S", "S", "E"],
      [null, "H", null, null, null, "W", null, null, null, null, null, "C", null],
      [null, "U", null, null, null, "O", null, null, "S", "T", "U", "H", "L"],
      [null, "N", "E", "B", "E", "L", null, null, null, null, null, "W", null],
      [null, "D", null, null, null, "K", "O", "E", "N", "I", "G", "I", "N"],
      ["K", null, "T", null, null, "E", null, null, null, null, null, "M", null],
      ["O", null, "A", null, null, null, null, null, null, "F", null, "M", null],
      ["E", null, "S", "C", "H", "O", "K", "O", "L", "A", "D", "E", null],
      ["N", null, "T", null, null, null, null, null, null, "M", null, "N", null],
      ["I", null, "A", null, null, null, null, null, null, "I", null, null, null],
      ["G", "I", "T", "A", "R", "R", "E", null, null, "L", null, null, null],
      [null, null, "U", null, null, null, null, null, "T", "I", "G", "E", "R"],
      [null, "B", "R", "U", "E", "C", "K", "E", null, "E", null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 6, answer: "STRASSE", clue: "Für Autos und Fußgänger gebaut" },
      { number: 2, dir: "down", row: 0, col: 11, answer: "SCHWIMMEN", clue: "Sportliche Fortbewegung im Wasser" },
      { number: 3, dir: "down", row: 1, col: 1, answer: "HUND", clue: "Bester Freund des Menschen" },
      { number: 4, dir: "down", row: 1, col: 5, answer: "WOLKE", clue: "Schwebt am Himmel, bringt Regen" },
      { number: 5, dir: "across", row: 2, col: 8, answer: "STUHL", clue: "Möbelstück zum Sitzen" },
      { number: 6, dir: "across", row: 3, col: 1, answer: "NEBEL", clue: "Trübt die Sicht am Morgen" },
      { number: 7, dir: "across", row: 4, col: 5, answer: "KOENIGIN", clue: "Weibliche Herrscherin" },
      { number: 8, dir: "down", row: 5, col: 0, answer: "KOENIG", clue: "Herrscher eines Königreichs" },
      { number: 9, dir: "down", row: 5, col: 2, answer: "TASTATUR", clue: "Zum Tippen am Computer" },
      { number: 10, dir: "down", row: 6, col: 9, answer: "FAMILIE", clue: "Eltern, Kinder und Verwandte" },
      { number: 11, dir: "across", row: 7, col: 2, answer: "SCHOKOLADE", clue: "Süße Nascherei aus Kakao" },
      { number: 12, dir: "across", row: 10, col: 0, answer: "GITARRE", clue: "Saiteninstrument zum Zupfen" },
      { number: 13, dir: "across", row: 11, col: 8, answer: "TIGER", clue: "Gestreifte Raubkatze" },
      { number: 14, dir: "across", row: 12, col: 1, answer: "BRUECKE", clue: "Führt über einen Fluss" },
    ],
  },
  {
    id: "cw-05",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, "D", null, null, "R", null, null, null, null, null, null, null],
      ["S", "T", "A", "D", "I", "O", "N", null, "M", "U", "S", "I", "K"],
      [null, null, "C", null, null, "B", null, null, null, null, null, null, "I"],
      [null, null, "H", null, null, "O", null, "K", "O", "F", "F", "E", "R"],
      [null, "F", null, "K", null, "T", null, null, null, "L", null, null, "C"],
      ["K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S", null, "H"],
      [null, "U", null, "O", null, "R", null, null, null, "G", null, null, "E"],
      [null, "E", null, "B", null, null, null, "M", null, "Z", null, "W", null],
      [null, "H", null, "L", null, null, null, "O", null, "E", null, "I", null],
      [null, "L", null, "A", null, "P", "I", "N", "G", "U", "I", "N", null],
      [null, "I", null, "U", null, null, null, "D", null, "G", null, "T", null],
      [null, "N", null, "C", null, null, null, null, null, null, null, "E", null],
      [null, "G", null, "H", "E", "R", "B", "S", "T", null, null, "R", null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 2, answer: "DACH", clue: "Oberer Abschluss eines Hauses" },
      { number: 2, dir: "down", row: 0, col: 5, answer: "ROBOTER", clue: "Maschine, die menschliche Arbeit übernimmt" },
      { number: 3, dir: "across", row: 1, col: 0, answer: "STADION", clue: "Großer Sportaustragungsort" },
      { number: 4, dir: "across", row: 1, col: 8, answer: "MUSIK", clue: "Klänge, die man hört und fühlt" },
      { number: 5, dir: "down", row: 1, col: 12, answer: "KIRCHE", clue: "Gebäude für Gottesdienste" },
      { number: 6, dir: "across", row: 3, col: 7, answer: "KOFFER", clue: "Für die Reise gepackt" },
      { number: 7, dir: "down", row: 3, col: 9, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
      { number: 8, dir: "down", row: 4, col: 1, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 9, dir: "down", row: 4, col: 3, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 10, dir: "across", row: 5, col: 0, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 11, dir: "down", row: 7, col: 7, answer: "MOND", clue: "Umkreist die Erde, wechselt seine Phasen" },
      { number: 12, dir: "down", row: 7, col: 11, answer: "WINTER", clue: "Kälteste Jahreszeit" },
      { number: 13, dir: "across", row: 9, col: 5, answer: "PINGUIN", clue: "Flugunfähiger Vogel der Antarktis" },
      { number: 14, dir: "across", row: 12, col: 3, answer: "HERBST", clue: "Jahreszeit mit buntem Laub" },
    ],
  },
  {
    id: "cw-06",
    rows: 13,
    cols: 13,
    grid: [
      [null, "B", "U", "S", null, null, null, null, null, null, null, null, null],
      [null, "I", null, "C", null, "K", null, "F", "L", "O", "E", "T", "E"],
      [null, "L", null, "H", null, "A", null, "E", null, null, null, null, null],
      [null, "D", null, "W", null, "R", null, "U", "R", "L", "A", "U", "B"],
      [null, "S", null, "I", null, "T", null, "E", null, null, null, null, null],
      [null, "C", null, "M", null, "O", null, "R", null, null, "W", null, null],
      [null, "H", null, "M", null, "F", null, "W", null, "H", "U", "H", "N"],
      [null, "I", null, "E", null, "F", null, "E", null, null, "E", null, null],
      ["K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S", null, "N"],
      [null, "M", null, null, null, "L", null, "R", null, null, "T", null, "U"],
      [null, null, null, null, null, null, null, null, "P", "F", "E", "R", "D"],
      [null, null, null, null, null, null, null, null, null, null, null, null, "E"],
      [null, null, null, null, null, null, null, null, null, null, "T", "A", "L"],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 1, answer: "BUS", clue: "Öffentliches Fahrzeug für viele Personen" },
      { number: 1, dir: "down", row: 0, col: 1, answer: "BILDSCHIRM", clue: "Zeigt Inhalte am Computer an" },
      { number: 2, dir: "down", row: 0, col: 3, answer: "SCHWIMMEN", clue: "Sportliche Fortbewegung im Wasser" },
      { number: 3, dir: "down", row: 1, col: 5, answer: "KARTOFFEL", clue: "Knolle, wird gekocht oder frittiert" },
      { number: 4, dir: "across", row: 1, col: 7, answer: "FLOETE", clue: "Wird geblasen, dünnes Rohr" },
      { number: 4, dir: "down", row: 1, col: 7, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 5, dir: "across", row: 3, col: 7, answer: "URLAUB", clue: "Freie Zeit zum Erholen" },
      { number: 6, dir: "down", row: 5, col: 10, answer: "WUESTE", clue: "Sehr trockenes Gebiet voller Sand" },
      { number: 7, dir: "across", row: 6, col: 9, answer: "HUHN", clue: "Legt Eier im Stall" },
      { number: 8, dir: "across", row: 8, col: 0, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 9, dir: "down", row: 8, col: 12, answer: "NUDEL", clue: "Aus Mehl, oft mit Soße serviert" },
      { number: 10, dir: "across", row: 10, col: 8, answer: "PFERD", clue: "Reittier mit Mähne" },
      { number: 11, dir: "across", row: 12, col: 10, answer: "TAL", clue: "Senke zwischen zwei Bergen" },
    ],
  },
  {
    id: "cw-07",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, null, "T", "I", "S", "C", "H"],
      [null, null, null, null, null, null, "F", null, "A", null, null, null, null],
      [null, null, "K", null, null, null, "A", null, "S", "T", "E", "R", "N"],
      ["K", "I", "N", "O", null, null, "H", null, "T", null, null, null, null],
      [null, null, "O", null, null, null, "R", null, "A", null, null, null, "S"],
      [null, null, "B", null, "T", null, "R", null, "T", null, "F", null, "C"],
      [null, null, "L", null, "H", null, "A", null, "U", null, "A", null, "H"],
      [null, "K", "A", "L", "E", "N", "D", "E", "R", null, "M", null, "L"],
      ["R", null, "U", null, "A", null, null, null, null, null, "I", null, "A"],
      ["O", null, "C", null, "T", null, null, "H", null, null, "L", null, "N"],
      ["S", "C", "H", "M", "E", "T", "T", "E", "R", "L", "I", "N", "G"],
      ["E", null, null, null, "R", null, null, "X", null, null, "E", null, "E"],
      [null, null, null, null, null, null, "W", "E", "I", "N", null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 8, answer: "TISCH", clue: "Möbelstück zum Essen und Arbeiten" },
      { number: 1, dir: "down", row: 0, col: 8, answer: "TASTATUR", clue: "Zum Tippen am Computer" },
      { number: 2, dir: "down", row: 1, col: 6, answer: "FAHRRAD", clue: "Zweirädriges Fahrzeug ohne Motor" },
      { number: 3, dir: "down", row: 2, col: 2, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 4, dir: "across", row: 2, col: 8, answer: "STERN", clue: "Leuchtet nachts am Himmel" },
      { number: 5, dir: "across", row: 3, col: 0, answer: "KINO", clue: "Ort zum Filmeschauen" },
      { number: 6, dir: "down", row: 4, col: 12, answer: "SCHLANGE", clue: "Beinloses Reptil" },
      { number: 7, dir: "down", row: 5, col: 4, answer: "THEATER", clue: "Ort für Bühnenstücke" },
      { number: 8, dir: "down", row: 5, col: 10, answer: "FAMILIE", clue: "Eltern, Kinder und Verwandte" },
      { number: 9, dir: "across", row: 7, col: 1, answer: "KALENDER", clue: "Zeigt Tage und Monate an" },
      { number: 10, dir: "down", row: 8, col: 0, answer: "ROSE", clue: "Blume mit Dornen, Symbol der Liebe" },
      { number: 11, dir: "down", row: 9, col: 7, answer: "HEXE", clue: "Fliegt im Märchen auf einem Besen" },
      { number: 12, dir: "across", row: 10, col: 0, answer: "SCHMETTERLING", clue: "Bunt geflügeltes Insekt" },
      { number: 13, dir: "across", row: 12, col: 6, answer: "WEIN", clue: "Alkoholisches Getränk aus Trauben" },
    ],
  },
  {
    id: "cw-08",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, null, "B", "R", "I", "E", "F"],
      [null, null, null, null, null, null, null, null, null, null, null, null, "L"],
      [null, "S", null, null, "F", null, "S", null, null, "F", null, null, "U"],
      ["S", "C", "H", "M", "E", "T", "T", "E", "R", "L", "I", "N", "G"],
      [null, "H", null, null, "U", null, "A", null, null, "U", null, null, "Z"],
      ["L", "O", "E", "W", "E", null, "D", null, null, "G", null, null, "E"],
      [null, "K", null, null, "R", null, "I", null, null, "H", null, null, "U"],
      [null, "O", null, null, "W", null, "O", null, null, "A", null, null, "G"],
      [null, "L", null, null, "E", null, "N", null, null, "F", null, null, null],
      [null, "A", null, null, "H", null, null, "W", "U", "E", "S", "T", "E"],
      [null, "D", null, null, "R", null, null, "I", null, "N", null, "A", null],
      ["M", "E", "E", "R", null, null, null, "N", null, null, null, "X", null],
      [null, null, null, null, null, "E", "R", "D", "E", null, "E", "I", "S"],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 8, answer: "BRIEF", clue: "Schriftliche Nachricht per Post" },
      { number: 2, dir: "down", row: 0, col: 12, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
      { number: 3, dir: "down", row: 2, col: 1, answer: "SCHOKOLADE", clue: "Süße Nascherei aus Kakao" },
      { number: 4, dir: "down", row: 2, col: 4, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 5, dir: "down", row: 2, col: 6, answer: "STADION", clue: "Großer Sportaustragungsort" },
      { number: 6, dir: "down", row: 2, col: 9, answer: "FLUGHAFEN", clue: "Wo Flugzeuge starten" },
      { number: 7, dir: "across", row: 3, col: 0, answer: "SCHMETTERLING", clue: "Bunt geflügeltes Insekt" },
      { number: 8, dir: "across", row: 5, col: 0, answer: "LOEWE", clue: "König der Tiere" },
      { number: 9, dir: "across", row: 9, col: 7, answer: "WUESTE", clue: "Sehr trockenes Gebiet voller Sand" },
      { number: 9, dir: "down", row: 9, col: 7, answer: "WIND", clue: "Bewegte Luft" },
      { number: 10, dir: "down", row: 9, col: 11, answer: "TAXI", clue: "Mietwagen mit Fahrer" },
      { number: 11, dir: "across", row: 11, col: 0, answer: "MEER", clue: "Große, salzige Wassermasse" },
      { number: 12, dir: "across", row: 12, col: 5, answer: "ERDE", clue: "Unser Heimatplanet" },
      { number: 13, dir: "across", row: 12, col: 10, answer: "EIS", clue: "Gefrorenes Wasser" },
    ],
  },
  {
    id: "cw-09",
    rows: 12,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, "S", "C", "H", "I", "F", "F", null],
      [null, "D", null, null, "S", null, null, null, null, null, "A", null, "P"],
      ["B", "R", "U", "E", "C", "K", "E", null, "F", null, "H", null, "O"],
      [null, "A", null, null, "H", null, null, null, "I", null, "R", null, "L"],
      [null, "C", null, null, "L", null, "M", "A", "L", "E", "R", "E", "I"],
      [null, "H", null, "R", "O", "S", "E", null, "M", null, "A", null, "Z"],
      [null, "E", null, null, "S", null, "D", null, null, null, "D", null, "E"],
      [null, null, "T", "A", "S", "T", "A", "T", "U", "R", null, null, "I"],
      [null, null, "O", null, null, null, "I", null, null, null, null, null, null],
      [null, "F", "R", "U", "E", "H", "L", "I", "N", "G", null, null, null],
      [null, null, null, null, null, null, "L", null, null, null, null, null, null],
      [null, "F", "L", "U", "G", "Z", "E", "U", "G", null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 6, answer: "SCHIFF", clue: "Fährt auf dem Wasser" },
      { number: 2, dir: "down", row: 0, col: 10, answer: "FAHRRAD", clue: "Zweirädriges Fahrzeug ohne Motor" },
      { number: 3, dir: "down", row: 1, col: 1, answer: "DRACHE", clue: "Feuerspeiendes Fabelwesen" },
      { number: 4, dir: "down", row: 1, col: 4, answer: "SCHLOSS", clue: "Prunkvolles Adelsgebäude" },
      { number: 5, dir: "down", row: 1, col: 12, answer: "POLIZEI", clue: "Sorgt für Sicherheit und Ordnung" },
      { number: 6, dir: "across", row: 2, col: 0, answer: "BRUECKE", clue: "Führt über einen Fluss" },
      { number: 7, dir: "down", row: 2, col: 8, answer: "FILM", clue: "Bewegte Bilder im Kino" },
      { number: 8, dir: "across", row: 4, col: 6, answer: "MALEREI", clue: "Kunst mit Pinsel und Farbe" },
      { number: 8, dir: "down", row: 4, col: 6, answer: "MEDAILLE", clue: "Auszeichnung für Sportler:innen" },
      { number: 9, dir: "across", row: 5, col: 3, answer: "ROSE", clue: "Blume mit Dornen, Symbol der Liebe" },
      { number: 10, dir: "across", row: 7, col: 2, answer: "TASTATUR", clue: "Zum Tippen am Computer" },
      { number: 10, dir: "down", row: 7, col: 2, answer: "TOR", clue: "Ziel beim Fußball" },
      { number: 11, dir: "across", row: 9, col: 1, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 12, dir: "across", row: 11, col: 1, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
    ],
  },
  {
    id: "cw-10",
    rows: 13,
    cols: 12,
    grid: [
      [null, null, null, null, null, null, null, null, null, null, "C", null],
      [null, null, null, null, null, null, null, null, "T", null, "O", null],
      [null, null, "S", null, null, "T", null, null, "R", null, "M", null],
      ["D", "A", "C", "H", null, "A", null, null, "O", null, "P", null],
      [null, null, "H", null, null, "S", null, null, "M", null, "U", null],
      ["B", "A", "L", "L", null, "T", null, null, "M", null, "T", null],
      [null, null, "A", null, "Z", "A", "U", "B", "E", "R", "E", "R"],
      ["T", "A", "N", "Z", null, "T", null, null, "L", null, "R", null],
      [null, null, "G", null, null, "U", null, null, null, "K", null, null],
      [null, "G", "E", "B", "U", "R", "T", "S", "T", "A", "G", null],
      [null, null, null, "U", null, null, null, null, null, "R", null, null],
      [null, "U", "H", "R", null, null, null, null, null, "T", null, null],
      [null, null, null, "G", null, "L", "A", "M", "P", "E", null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 10, answer: "COMPUTER", clue: "Elektronisches Rechengerät" },
      { number: 2, dir: "down", row: 1, col: 8, answer: "TROMMEL", clue: "Schlaginstrument" },
      { number: 3, dir: "down", row: 2, col: 2, answer: "SCHLANGE", clue: "Beinloses Reptil" },
      { number: 4, dir: "down", row: 2, col: 5, answer: "TASTATUR", clue: "Zum Tippen am Computer" },
      { number: 5, dir: "across", row: 3, col: 0, answer: "DACH", clue: "Oberer Abschluss eines Hauses" },
      { number: 6, dir: "across", row: 5, col: 0, answer: "BALL", clue: "Rundes Sportgerät" },
      { number: 7, dir: "across", row: 6, col: 4, answer: "ZAUBERER", clue: "Wirkt in Märchen mit Magie" },
      { number: 8, dir: "across", row: 7, col: 0, answer: "TANZ", clue: "Rhythmische Bewegung zur Musik" },
      { number: 9, dir: "down", row: 8, col: 9, answer: "KARTE", clue: "Zeigt Länder oder wird beim Spielen benutzt" },
      { number: 10, dir: "across", row: 9, col: 1, answer: "GEBURTSTAG", clue: "Jährlicher Feiertag der eigenen Geburt" },
      { number: 11, dir: "down", row: 9, col: 3, answer: "BURG", clue: "Mittelalterliche Festung" },
      { number: 12, dir: "across", row: 11, col: 1, answer: "UHR", clue: "Zeigt die Zeit an" },
      { number: 13, dir: "across", row: 12, col: 5, answer: "LAMPE", clue: "Spendet künstliches Licht" },
    ],
  },
  {
    id: "cw-11",
    rows: 13,
    cols: 13,
    grid: [
      ["G", "I", "T", "A", "R", "R", "E", null, null, null, "S", null, null],
      [null, null, null, null, null, "O", null, "F", null, null, "C", null, null],
      [null, "F", "U", "S", "S", "B", "A", "L", "L", null, "H", null, null],
      [null, null, null, null, null, "O", null, "U", null, null, "L", null, null],
      [null, null, "G", null, null, "T", null, "G", null, null, "O", null, null],
      ["K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S", null, null],
      [null, null, "R", null, null, "R", null, "A", null, null, "S", null, null],
      [null, null, "T", null, "K", null, null, "F", null, "D", null, null, "S"],
      [null, "F", "E", "U", "E", "R", "W", "E", "H", "R", null, null, "C"],
      [null, null, "N", null, "L", null, null, "N", null, "A", null, null, "H"],
      [null, "T", null, null, "L", null, null, null, null, "C", null, null, "N"],
      ["S", "O", "M", "M", "E", "R", null, null, null, "H", null, null, "E"],
      [null, "R", null, null, "R", null, null, "W", "U", "E", "S", "T", "E"],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 0, answer: "GITARRE", clue: "Saiteninstrument zum Zupfen" },
      { number: 2, dir: "down", row: 0, col: 5, answer: "ROBOTER", clue: "Maschine, die menschliche Arbeit übernimmt" },
      { number: 3, dir: "down", row: 0, col: 10, answer: "SCHLOSS", clue: "Prunkvolles Adelsgebäude" },
      { number: 4, dir: "down", row: 1, col: 7, answer: "FLUGHAFEN", clue: "Wo Flugzeuge starten" },
      { number: 5, dir: "across", row: 2, col: 1, answer: "FUSSBALL", clue: "Meistgespielte Ballsportart der Welt" },
      { number: 6, dir: "down", row: 4, col: 2, answer: "GARTEN", clue: "Grünfläche zum Anpflanzen" },
      { number: 7, dir: "across", row: 5, col: 0, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 8, dir: "down", row: 7, col: 4, answer: "KELLER", clue: "Unterster Raum eines Hauses" },
      { number: 9, dir: "down", row: 7, col: 9, answer: "DRACHE", clue: "Feuerspeiendes Fabelwesen" },
      { number: 10, dir: "down", row: 7, col: 12, answer: "SCHNEE", clue: "Weiße Winterflocken" },
      { number: 11, dir: "across", row: 8, col: 1, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 12, dir: "down", row: 10, col: 1, answer: "TOR", clue: "Ziel beim Fußball" },
      { number: 13, dir: "across", row: 11, col: 0, answer: "SOMMER", clue: "Wärmste Jahreszeit" },
      { number: 14, dir: "across", row: 12, col: 7, answer: "WUESTE", clue: "Sehr trockenes Gebiet voller Sand" },
    ],
  },
  {
    id: "cw-12",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, null, null, null, null, "R", null],
      [null, null, null, null, null, "K", "A", "L", "E", "N", "D", "E", "R"],
      ["T", "R", "A", "U", "M", null, "P", null, null, null, null, "G", null],
      ["E", null, null, null, null, "C", "O", "M", "P", "U", "T", "E", "R"],
      ["L", null, null, "Z", null, null, "T", null, null, null, null, "N", null],
      ["E", null, null, "W", null, null, "H", null, null, "K", null, null, null],
      ["F", "A", "M", "I", "L", "I", "E", null, "T", "A", "L", null, "T"],
      ["O", null, null, "E", null, null, "K", null, null, "P", null, null, "H"],
      ["N", null, null, "B", null, "M", "E", "D", "A", "I", "L", "L", "E"],
      [null, null, null, "E", null, null, null, null, null, "T", null, null, "A"],
      ["E", "S", "E", "L", null, null, null, null, null, "A", null, null, "T"],
      [null, null, null, null, "S", "P", "I", "E", "G", "E", "L", null, "E"],
      [null, null, null, null, null, null, null, null, null, "N", null, null, "R"],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 11, answer: "REGEN", clue: "Fällt aus Wolken" },
      { number: 2, dir: "across", row: 1, col: 5, answer: "KALENDER", clue: "Zeigt Tage und Monate an" },
      { number: 3, dir: "down", row: 1, col: 6, answer: "APOTHEKE", clue: "Verkauft Medikamente" },
      { number: 4, dir: "across", row: 2, col: 0, answer: "TRAUM", clue: "Erlebnis während des Schlafs" },
      { number: 4, dir: "down", row: 2, col: 0, answer: "TELEFON", clue: "Gerät zum Anrufen" },
      { number: 5, dir: "across", row: 3, col: 5, answer: "COMPUTER", clue: "Elektronisches Rechengerät" },
      { number: 6, dir: "down", row: 4, col: 3, answer: "ZWIEBEL", clue: "Macht beim Schneiden die Augen tränen" },
      { number: 7, dir: "down", row: 5, col: 9, answer: "KAPITAEN", clue: "Führt ein Schiff" },
      { number: 8, dir: "across", row: 6, col: 0, answer: "FAMILIE", clue: "Eltern, Kinder und Verwandte" },
      { number: 9, dir: "across", row: 6, col: 8, answer: "TAL", clue: "Senke zwischen zwei Bergen" },
      { number: 10, dir: "down", row: 6, col: 12, answer: "THEATER", clue: "Ort für Bühnenstücke" },
      { number: 11, dir: "across", row: 8, col: 5, answer: "MEDAILLE", clue: "Auszeichnung für Sportler:innen" },
      { number: 12, dir: "across", row: 10, col: 0, answer: "ESEL", clue: "Störrisches Lasttier" },
      { number: 13, dir: "across", row: 11, col: 4, answer: "SPIEGEL", clue: "Zeigt das eigene Bild" },
    ],
  },
  {
    id: "cw-13",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, "K", null, "B", "A", "E", "C", "K", "E", "R", null, null],
      [null, null, "A", null, null, null, null, null, "N", null, null, null, "D"],
      [null, null, "P", null, null, "F", null, "K", "O", "F", "F", "E", "R"],
      [null, null, "I", "N", "S", "E", "L", null, "B", null, "R", null, "A"],
      [null, null, "T", null, null, "U", null, null, "L", null, "O", null, "C"],
      ["K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S", null, "H"],
      ["O", null, "E", null, null, "R", null, null, "U", null, "C", null, "E"],
      ["N", null, "N", null, null, "W", null, null, "C", null, "H", null, null],
      ["Z", null, null, "T", null, "E", null, null, "H", null, null, null, null],
      ["E", null, null, "I", null, "H", null, null, null, "R", null, null, null],
      ["R", null, null, "G", "I", "R", "A", "F", "F", "E", null, null, null],
      ["T", null, null, "E", null, null, null, null, null, "I", null, null, null],
      [null, null, "B", "R", "I", "E", "F", null, null, "S", null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 2, answer: "KAPITAEN", clue: "Führt ein Schiff" },
      { number: 2, dir: "across", row: 0, col: 4, answer: "BAECKER", clue: "Backt Brot und Brötchen" },
      { number: 3, dir: "down", row: 0, col: 8, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 4, dir: "down", row: 1, col: 12, answer: "DRACHE", clue: "Feuerspeiendes Fabelwesen" },
      { number: 5, dir: "down", row: 2, col: 5, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 6, dir: "across", row: 2, col: 7, answer: "KOFFER", clue: "Für die Reise gepackt" },
      { number: 7, dir: "down", row: 2, col: 10, answer: "FROSCH", clue: "Springt und quakt am Teich" },
      { number: 8, dir: "across", row: 3, col: 2, answer: "INSEL", clue: "Von Wasser umgebenes Land" },
      { number: 9, dir: "across", row: 5, col: 0, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 9, dir: "down", row: 5, col: 0, answer: "KONZERT", clue: "Live-Musikveranstaltung" },
      { number: 10, dir: "down", row: 8, col: 3, answer: "TIGER", clue: "Gestreifte Raubkatze" },
      { number: 11, dir: "down", row: 9, col: 9, answer: "REIS", clue: "Kleines weißes Getreidekorn als Beilage" },
      { number: 12, dir: "across", row: 10, col: 3, answer: "GIRAFFE", clue: "Tier mit dem längsten Hals" },
      { number: 13, dir: "across", row: 12, col: 2, answer: "BRIEF", clue: "Schriftliche Nachricht per Post" },
    ],
  },
  {
    id: "cw-14",
    rows: 13,
    cols: 13,
    grid: [
      ["W", "A", "S", "S", "E", "R", null, null, null, null, null, null, null],
      [null, null, "T", null, "N", null, null, null, "F", null, null, null, null],
      [null, "T", "A", "S", "T", "A", "T", "U", "R", null, null, "Z", null],
      [null, null, "D", null, "E", null, null, null, "U", null, "E", "I", "S"],
      [null, null, "I", null, null, null, null, null, "E", null, null, "T", null],
      ["K", "N", "O", "B", "L", "A", "U", "C", "H", null, null, "R", null],
      ["O", null, "N", null, null, null, null, null, "L", null, null, "O", null],
      ["F", null, null, null, null, null, "P", null, "I", null, null, "N", null],
      ["F", "U", "C", "H", "S", null, "F", "E", "N", "S", "T", "E", "R"],
      ["E", null, null, null, "C", null, "E", null, "G", null, "A", null, null],
      ["R", null, null, null, "H", null, "R", null, null, null, "N", null, null],
      [null, null, null, null, "A", null, "D", null, null, null, "Z", null, null],
      [null, null, null, null, "F", null, null, null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 0, answer: "WASSER", clue: "Lebensnotwendige, farblose Flüssigkeit" },
      { number: 2, dir: "down", row: 0, col: 2, answer: "STADION", clue: "Großer Sportaustragungsort" },
      { number: 3, dir: "down", row: 0, col: 4, answer: "ENTE", clue: "Watschelt und quakt am Teich" },
      { number: 4, dir: "down", row: 1, col: 8, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 5, dir: "across", row: 2, col: 1, answer: "TASTATUR", clue: "Zum Tippen am Computer" },
      { number: 6, dir: "down", row: 2, col: 11, answer: "ZITRONE", clue: "Saure gelbe Frucht" },
      { number: 7, dir: "across", row: 3, col: 10, answer: "EIS", clue: "Gefrorenes Wasser" },
      { number: 8, dir: "across", row: 5, col: 0, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 8, dir: "down", row: 5, col: 0, answer: "KOFFER", clue: "Für die Reise gepackt" },
      { number: 9, dir: "down", row: 7, col: 6, answer: "PFERD", clue: "Reittier mit Mähne" },
      { number: 10, dir: "across", row: 8, col: 0, answer: "FUCHS", clue: "Schlaues, rotes Waldtier" },
      { number: 11, dir: "down", row: 8, col: 4, answer: "SCHAF", clue: "Wolliges Weidetier" },
      { number: 12, dir: "across", row: 8, col: 6, answer: "FENSTER", clue: "Durchsichtige Öffnung in der Wand" },
      { number: 13, dir: "down", row: 8, col: 10, answer: "TANZ", clue: "Rhythmische Bewegung zur Musik" },
    ],
  },
  {
    id: "cw-15",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, null, "L", "A", "M", "P", "E"],
      [null, null, null, null, null, null, null, "M", null, null, null, "O", null],
      ["Z", null, "S", null, null, "W", "U", "E", "R", "F", "E", "L", null],
      ["A", null, "C", null, "T", null, null, "D", null, null, null, "I", null],
      ["U", null, "H", null, "A", null, null, "A", null, "A", null, "Z", null],
      ["B", "I", "L", "D", "S", "C", "H", "I", "R", "M", null, "E", null],
      ["E", null, "A", null, "T", null, null, "L", null, "P", null, "I", null],
      ["R", null, "N", null, "A", null, null, "L", null, "E", null, null, null],
      ["E", null, "G", null, "T", null, null, "E", null, "L", "U", "F", "T"],
      ["R", null, "E", null, "U", null, null, null, "B", null, null, null, null],
      [null, null, null, "O", "R", "A", "N", "G", "E", null, null, null, null],
      [null, null, null, null, null, null, null, null, "T", null, null, null, null],
      [null, null, null, null, null, null, null, null, "T", "A", "N", "Z", null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 8, answer: "LAMPE", clue: "Spendet künstliches Licht" },
      { number: 2, dir: "down", row: 0, col: 11, answer: "POLIZEI", clue: "Sorgt für Sicherheit und Ordnung" },
      { number: 3, dir: "down", row: 1, col: 7, answer: "MEDAILLE", clue: "Auszeichnung für Sportler:innen" },
      { number: 4, dir: "down", row: 2, col: 0, answer: "ZAUBERER", clue: "Wirkt in Märchen mit Magie" },
      { number: 5, dir: "down", row: 2, col: 2, answer: "SCHLANGE", clue: "Beinloses Reptil" },
      { number: 6, dir: "across", row: 2, col: 5, answer: "WUERFEL", clue: "Sechsseitiger Zufallsgeber beim Spielen" },
      { number: 7, dir: "down", row: 3, col: 4, answer: "TASTATUR", clue: "Zum Tippen am Computer" },
      { number: 8, dir: "down", row: 4, col: 9, answer: "AMPEL", clue: "Regelt den Verkehr mit Farben" },
      { number: 9, dir: "across", row: 5, col: 0, answer: "BILDSCHIRM", clue: "Zeigt Inhalte am Computer an" },
      { number: 10, dir: "across", row: 8, col: 9, answer: "LUFT", clue: "Zum Atmen nötiges Gas-Gemisch" },
      { number: 11, dir: "down", row: 9, col: 8, answer: "BETT", clue: "Möbelstück zum Schlafen" },
      { number: 12, dir: "across", row: 10, col: 3, answer: "ORANGE", clue: "Runde Zitrusfrucht" },
      { number: 13, dir: "across", row: 12, col: 8, answer: "TANZ", clue: "Rhythmische Bewegung zur Musik" },
    ],
  },
  {
    id: "cw-16",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, "P", "F", "E", "F", "F", "E", "R", null, null, null, null],
      [null, null, null, null, "I", null, null, null, "O", null, null, null, null],
      [null, null, null, null, "S", null, null, null, "B", "L", "I", "T", "Z"],
      [null, null, null, null, null, null, null, null, "O", null, null, "O", null],
      [null, null, null, null, null, null, "G", "I", "T", "A", "R", "R", "E"],
      ["S", null, null, "T", null, null, null, null, "E", null, null, null, "L"],
      ["T", null, "K", "A", "E", "N", "G", "U", "R", "U", null, null, "E"],
      ["U", null, null, "S", null, null, null, null, null, null, null, null, "F"],
      ["R", null, null, "T", null, null, null, null, "P", "I", "Z", "Z", "A"],
      ["M", "E", "D", "A", "I", "L", "L", "E", null, null, null, null, "N"],
      [null, null, null, "T", null, null, null, null, null, null, null, null, "T"],
      [null, "F", "L", "U", "G", "H", "A", "F", "E", "N", null, null, null],
      [null, null, null, "R", null, null, null, null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 2, answer: "PFEFFER", clue: "Scharfes Gewürz aus kleinen Körnern" },
      { number: 2, dir: "down", row: 0, col: 4, answer: "EIS", clue: "Gefrorenes Wasser" },
      { number: 3, dir: "down", row: 0, col: 8, answer: "ROBOTER", clue: "Maschine, die menschliche Arbeit übernimmt" },
      { number: 4, dir: "across", row: 2, col: 8, answer: "BLITZ", clue: "Leuchtet kurz vor dem Donner" },
      { number: 5, dir: "down", row: 2, col: 11, answer: "TOR", clue: "Ziel beim Fußball" },
      { number: 6, dir: "across", row: 4, col: 6, answer: "GITARRE", clue: "Saiteninstrument zum Zupfen" },
      { number: 7, dir: "down", row: 4, col: 12, answer: "ELEFANT", clue: "Größtes Landsäugetier" },
      { number: 8, dir: "down", row: 5, col: 0, answer: "STURM", clue: "Sehr starker Wind" },
      { number: 9, dir: "down", row: 5, col: 3, answer: "TASTATUR", clue: "Zum Tippen am Computer" },
      { number: 10, dir: "across", row: 6, col: 2, answer: "KAENGURU", clue: "Australisches Beuteltier" },
      { number: 11, dir: "across", row: 8, col: 8, answer: "PIZZA", clue: "Italienisches Fladengericht mit Belag" },
      { number: 12, dir: "across", row: 9, col: 0, answer: "MEDAILLE", clue: "Auszeichnung für Sportler:innen" },
      { number: 13, dir: "across", row: 11, col: 1, answer: "FLUGHAFEN", clue: "Wo Flugzeuge starten" },
    ],
  },
  {
    id: "cw-17",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, "G", null, null, "B", "L", "A", "T", "T", null],
      ["K", "A", "T", "Z", "E", null, null, "L", null, null, "I", null, null],
      [null, null, null, null, "I", null, "F", "U", "C", "H", "S", null, null],
      [null, null, null, null, "G", null, null, "M", null, null, "C", null, null],
      [null, "B", "R", "U", "E", "C", "K", "E", null, null, "H", null, null],
      ["S", null, null, null, null, null, "R", null, "F", null, null, "S", null],
      ["C", null, "P", null, "K", "N", "O", "B", "L", "A", "U", "C", "H"],
      ["H", null, "I", null, null, null, "K", null, "U", null, null, "H", null],
      ["L", null, "N", null, null, null, "O", null, "G", null, null, "L", null],
      ["O", null, "G", null, null, null, "D", null, "Z", null, null, "A", null],
      ["S", null, "U", null, null, null, "I", null, "E", null, null, "N", null],
      ["S", "P", "I", "E", "G", "E", "L", null, "U", null, null, "G", null],
      [null, null, "N", null, null, null, null, null, "G", null, null, "E", null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 4, answer: "GEIGE", clue: "Kleines Streichinstrument" },
      { number: 2, dir: "across", row: 0, col: 7, answer: "BLATT", clue: "Grüner Teil einer Pflanze" },
      { number: 2, dir: "down", row: 0, col: 7, answer: "BLUME", clue: "Bunte, duftende Pflanze" },
      { number: 3, dir: "down", row: 0, col: 10, answer: "TISCH", clue: "Möbelstück zum Essen und Arbeiten" },
      { number: 4, dir: "across", row: 1, col: 0, answer: "KATZE", clue: "Schnurrendes Haustier" },
      { number: 5, dir: "across", row: 2, col: 6, answer: "FUCHS", clue: "Schlaues, rotes Waldtier" },
      { number: 6, dir: "across", row: 4, col: 1, answer: "BRUECKE", clue: "Führt über einen Fluss" },
      { number: 7, dir: "down", row: 4, col: 6, answer: "KROKODIL", clue: "Reptil mit vielen scharfen Zähnen im Wasser" },
      { number: 8, dir: "down", row: 5, col: 0, answer: "SCHLOSS", clue: "Prunkvolles Adelsgebäude" },
      { number: 9, dir: "down", row: 5, col: 8, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
      { number: 10, dir: "down", row: 5, col: 11, answer: "SCHLANGE", clue: "Beinloses Reptil" },
      { number: 11, dir: "down", row: 6, col: 2, answer: "PINGUIN", clue: "Flugunfähiger Vogel der Antarktis" },
      { number: 12, dir: "across", row: 6, col: 4, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 13, dir: "across", row: 11, col: 0, answer: "SPIEGEL", clue: "Zeigt das eigene Bild" },
    ],
  },
  {
    id: "cw-18",
    rows: 13,
    cols: 13,
    grid: [
      [null, "W", null, null, null, null, null, "K", null, null, "G", null, null],
      [null, "O", null, "S", "C", "H", "L", "A", "N", "G", "E", null, null],
      [null, "L", null, null, null, null, null, "E", null, null, "B", null, null],
      [null, "K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S", null],
      [null, "E", null, null, null, null, null, "G", null, null, "R", null, null],
      [null, null, null, null, null, null, null, "U", null, null, "T", "E", "E"],
      ["C", "O", "M", "P", "U", "T", "E", "R", null, null, "S", null, null],
      [null, "S", null, "I", null, "H", null, "U", null, null, "T", null, null],
      [null, "T", null, "N", null, "E", null, null, "S", "P", "A", "T", "Z"],
      ["B", "E", "R", "G", null, "A", null, null, null, null, "G", null, null],
      [null, "R", null, "U", null, "T", "I", "G", "E", "R", null, null, null],
      [null, "N", null, "I", null, "E", null, null, null, null, null, null, null],
      [null, null, null, "N", null, "R", "E", "I", "S", null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 1, answer: "WOLKE", clue: "Schwebt am Himmel, bringt Regen" },
      { number: 2, dir: "down", row: 0, col: 7, answer: "KAENGURU", clue: "Australisches Beuteltier" },
      { number: 3, dir: "down", row: 0, col: 10, answer: "GEBURTSTAG", clue: "Jährlicher Feiertag der eigenen Geburt" },
      { number: 4, dir: "across", row: 1, col: 3, answer: "SCHLANGE", clue: "Beinloses Reptil" },
      { number: 5, dir: "across", row: 3, col: 1, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 6, dir: "across", row: 5, col: 10, answer: "TEE", clue: "Aufgussgetränk aus Blättern" },
      { number: 7, dir: "across", row: 6, col: 0, answer: "COMPUTER", clue: "Elektronisches Rechengerät" },
      { number: 8, dir: "down", row: 6, col: 1, answer: "OSTERN", clue: "Fest mit Eiern und Hasen im Frühling" },
      { number: 9, dir: "down", row: 6, col: 3, answer: "PINGUIN", clue: "Flugunfähiger Vogel der Antarktis" },
      { number: 10, dir: "down", row: 6, col: 5, answer: "THEATER", clue: "Ort für Bühnenstücke" },
      { number: 11, dir: "across", row: 8, col: 8, answer: "SPATZ", clue: "Kleiner, häufiger Stadtvogel" },
      { number: 12, dir: "across", row: 9, col: 0, answer: "BERG", clue: "Hohe Erhebung der Landschaft" },
      { number: 13, dir: "across", row: 10, col: 5, answer: "TIGER", clue: "Gestreifte Raubkatze" },
      { number: 14, dir: "across", row: 12, col: 5, answer: "REIS", clue: "Kleines weißes Getreidekorn als Beilage" },
    ],
  },
  {
    id: "cw-19",
    rows: 13,
    cols: 13,
    grid: [
      ["F", null, null, null, "B", null, null, "M", "U", "S", "I", "K", null],
      ["E", "L", "E", "F", "A", "N", "T", null, null, null, null, "O", null],
      ["N", null, null, null, "U", null, null, null, "K", null, null, "E", null],
      ["S", "C", "H", "M", "E", "T", "T", "E", "R", "L", "I", "N", "G"],
      ["T", null, null, null, "R", null, null, null, "A", null, null, "I", null],
      ["E", null, "H", null, null, null, null, null, "N", null, null, "G", null],
      ["R", null, "A", "P", "O", "T", "H", "E", "K", "E", null, "I", null],
      [null, null, "U", null, null, null, null, null, "E", null, null, "N", null],
      [null, null, "S", null, null, "G", null, null, "N", null, null, null, null],
      [null, null, null, "M", "A", "E", "R", "C", "H", "E", "N", null, null],
      [null, null, null, null, null, "I", null, null, "A", null, null, null, null],
      [null, null, "F", "L", "U", "G", "Z", "E", "U", "G", null, null, null],
      [null, null, null, null, null, "E", null, null, "S", null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 0, answer: "FENSTER", clue: "Durchsichtige Öffnung in der Wand" },
      { number: 2, dir: "down", row: 0, col: 4, answer: "BAUER", clue: "Bewirtschaftet Felder und Höfe" },
      { number: 3, dir: "across", row: 0, col: 7, answer: "MUSIK", clue: "Klänge, die man hört und fühlt" },
      { number: 4, dir: "down", row: 0, col: 11, answer: "KOENIGIN", clue: "Weibliche Herrscherin" },
      { number: 5, dir: "across", row: 1, col: 0, answer: "ELEFANT", clue: "Größtes Landsäugetier" },
      { number: 6, dir: "down", row: 2, col: 8, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 7, dir: "across", row: 3, col: 0, answer: "SCHMETTERLING", clue: "Bunt geflügeltes Insekt" },
      { number: 8, dir: "down", row: 5, col: 2, answer: "HAUS", clue: "Wo man wohnt" },
      { number: 9, dir: "across", row: 6, col: 2, answer: "APOTHEKE", clue: "Verkauft Medikamente" },
      { number: 10, dir: "down", row: 8, col: 5, answer: "GEIGE", clue: "Kleines Streichinstrument" },
      { number: 11, dir: "across", row: 9, col: 3, answer: "MAERCHEN", clue: "Fantastische Erzählung für Kinder" },
      { number: 12, dir: "across", row: 11, col: 2, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
    ],
  },
  {
    id: "cw-20",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, "L", null, null, null, null, "M", null, null],
      [null, null, null, null, "M", "A", "E", "R", "C", "H", "E", "N", null],
      [null, "B", null, null, null, "U", null, null, null, null, "D", null, "E"],
      [null, "R", null, null, null, "F", "U", "S", "S", "B", "A", "L", "L"],
      [null, "U", null, null, null, "E", null, "C", null, null, "I", null, "E"],
      [null, "N", null, "K", null, "N", null, "H", null, null, "L", null, "F"],
      [null, "N", null, "O", null, null, null, "O", null, null, "L", null, "A"],
      ["G", "E", "S", "C", "H", "E", "N", "K", null, "W", "E", "I", "N"],
      [null, "N", null, "H", null, null, null, "O", null, null, null, null, "T"],
      ["R", null, null, null, null, null, null, "L", null, null, null, null, null],
      ["E", null, "K", "A", "P", "I", "T", "A", "E", "N", null, null, null],
      ["I", null, null, null, null, null, null, "D", null, null, null, null, null],
      ["S", "C", "H", "M", "E", "T", "T", "E", "R", "L", "I", "N", "G"],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 5, answer: "LAUFEN", clue: "Sport, bei dem man ausdauernd rennt" },
      { number: 2, dir: "down", row: 0, col: 10, answer: "MEDAILLE", clue: "Auszeichnung für Sportler:innen" },
      { number: 3, dir: "across", row: 1, col: 4, answer: "MAERCHEN", clue: "Fantastische Erzählung für Kinder" },
      { number: 4, dir: "down", row: 2, col: 1, answer: "BRUNNEN", clue: "Ort, an dem Wasser gefördert wird" },
      { number: 5, dir: "down", row: 2, col: 12, answer: "ELEFANT", clue: "Größtes Landsäugetier" },
      { number: 6, dir: "across", row: 3, col: 5, answer: "FUSSBALL", clue: "Meistgespielte Ballsportart der Welt" },
      { number: 7, dir: "down", row: 3, col: 7, answer: "SCHOKOLADE", clue: "Süße Nascherei aus Kakao" },
      { number: 8, dir: "down", row: 5, col: 3, answer: "KOCH", clue: "Bereitet Speisen im Restaurant zu" },
      { number: 9, dir: "across", row: 7, col: 0, answer: "GESCHENK", clue: "Wird zum Geburtstag überreicht" },
      { number: 10, dir: "across", row: 7, col: 9, answer: "WEIN", clue: "Alkoholisches Getränk aus Trauben" },
      { number: 11, dir: "down", row: 9, col: 0, answer: "REIS", clue: "Kleines weißes Getreidekorn als Beilage" },
      { number: 12, dir: "across", row: 10, col: 2, answer: "KAPITAEN", clue: "Führt ein Schiff" },
      { number: 13, dir: "across", row: 12, col: 0, answer: "SCHMETTERLING", clue: "Bunt geflügeltes Insekt" },
    ],
  },
  {
    id: "cw-21",
    rows: 13,
    cols: 13,
    grid: [
      [null, "T", "H", "E", "A", "T", "E", "R", null, null, null, null, null],
      [null, null, null, null, null, "E", null, null, "M", null, null, null, null],
      ["M", null, null, "P", "O", "L", "I", "Z", "E", "I", null, null, null],
      ["U", null, null, null, null, "E", null, null, "D", null, null, null, null],
      ["S", "C", "H", "L", "A", "F", null, null, "A", null, "F", null, "S"],
      ["E", null, null, null, null, "O", null, null, "I", null, "R", null, "C"],
      ["U", null, "Z", null, "K", "N", "O", "B", "L", "A", "U", "C", "H"],
      ["M", null, "U", null, null, null, null, null, "L", null, "E", null, "W"],
      [null, null, "G", "I", "R", "A", "F", "F", "E", null, "H", null, "I"],
      [null, null, null, null, null, null, null, null, null, null, "L", null, "M"],
      [null, null, null, "B", "I", "L", "D", "S", "C", "H", "I", "R", "M"],
      [null, null, null, null, null, null, null, null, null, null, "N", null, "E"],
      [null, null, null, "F", "L", "U", "G", "Z", "E", "U", "G", null, "N"],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 1, answer: "THEATER", clue: "Ort für Bühnenstücke" },
      { number: 2, dir: "down", row: 0, col: 5, answer: "TELEFON", clue: "Gerät zum Anrufen" },
      { number: 3, dir: "down", row: 1, col: 8, answer: "MEDAILLE", clue: "Auszeichnung für Sportler:innen" },
      { number: 4, dir: "down", row: 2, col: 0, answer: "MUSEUM", clue: "Ort für Kunst und Ausstellungen" },
      { number: 5, dir: "across", row: 2, col: 3, answer: "POLIZEI", clue: "Sorgt für Sicherheit und Ordnung" },
      { number: 6, dir: "across", row: 4, col: 0, answer: "SCHLAF", clue: "Nächtliche Erholung" },
      { number: 7, dir: "down", row: 4, col: 10, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 8, dir: "down", row: 4, col: 12, answer: "SCHWIMMEN", clue: "Sportliche Fortbewegung im Wasser" },
      { number: 9, dir: "down", row: 6, col: 2, answer: "ZUG", clue: "Fährt auf Schienen" },
      { number: 10, dir: "across", row: 6, col: 4, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 11, dir: "across", row: 8, col: 2, answer: "GIRAFFE", clue: "Tier mit dem längsten Hals" },
      { number: 12, dir: "across", row: 10, col: 3, answer: "BILDSCHIRM", clue: "Zeigt Inhalte am Computer an" },
      { number: 13, dir: "across", row: 12, col: 3, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
    ],
  },
  {
    id: "cw-22",
    rows: 13,
    cols: 12,
    grid: [
      ["S", null, "A", null, null, "Z", "I", "E", "G", "E", null, null],
      ["A", "M", "P", "E", "L", null, null, null, "U", null, null, null],
      ["L", null, "F", null, null, null, null, "P", "R", "I", "N", "Z"],
      ["Z", null, "E", null, null, null, null, null, "K", null, null, null],
      [null, "F", "L", "U", "G", "H", "A", "F", "E", "N", null, null],
      [null, null, null, null, null, null, null, "E", null, null, null, null],
      [null, "K", "N", "O", "B", "L", "A", "U", "C", "H", null, null],
      ["S", null, null, null, null, null, null, "E", null, "A", null, null],
      ["T", "A", "S", "T", "A", "T", "U", "R", null, "I", null, null],
      ["E", null, null, null, null, null, null, "W", null, null, null, null],
      ["R", null, "G", "E", "S", "C", "H", "E", "N", "K", null, null],
      ["N", null, null, null, null, null, null, "H", null, null, null, null],
      [null, "K", "A", "E", "N", "G", "U", "R", "U", null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 0, answer: "SALZ", clue: "Würzt fast jedes Gericht" },
      { number: 2, dir: "down", row: 0, col: 2, answer: "APFEL", clue: "Rundes Obst, hält den Doktor fern" },
      { number: 3, dir: "across", row: 0, col: 5, answer: "ZIEGE", clue: "Meckerndes Hoftier mit Hörnern" },
      { number: 4, dir: "down", row: 0, col: 8, answer: "GURKE", clue: "Grünes, längliches Gemüse" },
      { number: 5, dir: "across", row: 1, col: 0, answer: "AMPEL", clue: "Regelt den Verkehr mit Farben" },
      { number: 6, dir: "across", row: 2, col: 7, answer: "PRINZ", clue: "Sohn eines Königs" },
      { number: 7, dir: "across", row: 4, col: 1, answer: "FLUGHAFEN", clue: "Wo Flugzeuge starten" },
      { number: 8, dir: "down", row: 4, col: 7, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 9, dir: "across", row: 6, col: 1, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 10, dir: "down", row: 6, col: 9, answer: "HAI", clue: "Gefürchteter Meeresräuber mit vielen Zähnen" },
      { number: 11, dir: "down", row: 7, col: 0, answer: "STERN", clue: "Leuchtet nachts am Himmel" },
      { number: 12, dir: "across", row: 8, col: 0, answer: "TASTATUR", clue: "Zum Tippen am Computer" },
      { number: 13, dir: "across", row: 10, col: 2, answer: "GESCHENK", clue: "Wird zum Geburtstag überreicht" },
      { number: 14, dir: "across", row: 12, col: 1, answer: "KAENGURU", clue: "Australisches Beuteltier" },
    ],
  },
  {
    id: "cw-23",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, "F", null, null, null, null, null, null],
      [null, "P", "F", "E", "F", "F", "E", "R", null, null, null, null, null],
      [null, null, null, null, "R", null, "U", null, null, null, "S", "K", "I"],
      ["C", "O", "M", "P", "U", "T", "E", "R", null, null, null, "A", null],
      [null, null, null, null, "E", null, "R", null, null, null, null, "L", null],
      [null, "F", null, null, "H", null, null, null, "Z", null, null, "E", null],
      [null, "A", null, "F", "L", "U", "G", "H", "A", "F", "E", "N", null],
      [null, "H", null, null, "I", null, null, null, "U", null, null, "D", null],
      ["B", "R", "U", "N", "N", "E", "N", null, "B", "A", "U", "E", "R"],
      [null, "R", null, null, "G", null, null, null, "E", null, null, "R", null],
      ["T", "A", "X", "I", null, "L", "E", "H", "R", "E", "R", null, null],
      [null, "D", null, null, null, null, null, null, "E", null, null, null, null],
      [null, null, null, null, null, "Z", "I", "T", "R", "O", "N", "E", null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 6, answer: "FEUER", clue: "Heiß, hell, verbrennt Holz" },
      { number: 2, dir: "across", row: 1, col: 1, answer: "PFEFFER", clue: "Scharfes Gewürz aus kleinen Körnern" },
      { number: 3, dir: "down", row: 1, col: 4, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 4, dir: "across", row: 2, col: 10, answer: "SKI", clue: "Damit gleitet man den Berg hinunter" },
      { number: 5, dir: "down", row: 2, col: 11, answer: "KALENDER", clue: "Zeigt Tage und Monate an" },
      { number: 6, dir: "across", row: 3, col: 0, answer: "COMPUTER", clue: "Elektronisches Rechengerät" },
      { number: 7, dir: "down", row: 5, col: 1, answer: "FAHRRAD", clue: "Zweirädriges Fahrzeug ohne Motor" },
      { number: 8, dir: "down", row: 5, col: 8, answer: "ZAUBERER", clue: "Wirkt in Märchen mit Magie" },
      { number: 9, dir: "across", row: 6, col: 3, answer: "FLUGHAFEN", clue: "Wo Flugzeuge starten" },
      { number: 10, dir: "across", row: 8, col: 0, answer: "BRUNNEN", clue: "Ort, an dem Wasser gefördert wird" },
      { number: 11, dir: "across", row: 8, col: 8, answer: "BAUER", clue: "Bewirtschaftet Felder und Höfe" },
      { number: 12, dir: "across", row: 10, col: 0, answer: "TAXI", clue: "Mietwagen mit Fahrer" },
      { number: 13, dir: "across", row: 10, col: 5, answer: "LEHRER", clue: "Unterrichtet in der Schule" },
      { number: 14, dir: "across", row: 12, col: 5, answer: "ZITRONE", clue: "Saure gelbe Frucht" },
    ],
  },
  {
    id: "cw-24",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, "R", null, null, null, null, null],
      ["W", null, null, null, "N", "E", "B", "E", "L", null, null, "O", null],
      ["O", null, null, null, null, null, null, "G", null, "B", null, "S", null],
      ["L", null, null, null, null, "E", "L", "E", "F", "A", "N", "T", null],
      ["K", "A", "T", "Z", "E", null, null, "N", null, "H", null, "E", null],
      ["E", null, "R", null, null, null, null, null, null, "N", null, "R", null],
      [null, null, "A", null, null, "G", "E", "S", "C", "H", "E", "N", "K"],
      [null, null, "U", null, null, "I", null, null, null, "O", null, null, "U"],
      [null, null, "B", "U", "T", "T", "E", "R", null, "F", null, null, "C"],
      [null, null, "E", null, null, "A", null, null, null, null, null, null, "H"],
      [null, null, null, "G", "I", "R", "A", "F", "F", "E", null, null, "E"],
      [null, null, null, null, null, "R", null, null, null, null, null, null, "N"],
      ["P", "O", "L", "I", "Z", "E", "I", null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 7, answer: "REGEN", clue: "Fällt aus Wolken" },
      { number: 2, dir: "down", row: 1, col: 0, answer: "WOLKE", clue: "Schwebt am Himmel, bringt Regen" },
      { number: 3, dir: "across", row: 1, col: 4, answer: "NEBEL", clue: "Trübt die Sicht am Morgen" },
      { number: 4, dir: "down", row: 1, col: 11, answer: "OSTERN", clue: "Fest mit Eiern und Hasen im Frühling" },
      { number: 5, dir: "down", row: 2, col: 9, answer: "BAHNHOF", clue: "Wo Züge abfahren" },
      { number: 6, dir: "across", row: 3, col: 5, answer: "ELEFANT", clue: "Größtes Landsäugetier" },
      { number: 7, dir: "across", row: 4, col: 0, answer: "KATZE", clue: "Schnurrendes Haustier" },
      { number: 8, dir: "down", row: 4, col: 2, answer: "TRAUBE", clue: "Wird zu Wein verarbeitet" },
      { number: 9, dir: "across", row: 6, col: 5, answer: "GESCHENK", clue: "Wird zum Geburtstag überreicht" },
      { number: 9, dir: "down", row: 6, col: 5, answer: "GITARRE", clue: "Saiteninstrument zum Zupfen" },
      { number: 10, dir: "down", row: 6, col: 12, answer: "KUCHEN", clue: "Süßes Gebäck zum Kaffee" },
      { number: 11, dir: "across", row: 8, col: 2, answer: "BUTTER", clue: "Streichfett aus Milch" },
      { number: 12, dir: "across", row: 10, col: 3, answer: "GIRAFFE", clue: "Tier mit dem längsten Hals" },
      { number: 13, dir: "across", row: 12, col: 0, answer: "POLIZEI", clue: "Sorgt für Sicherheit und Ordnung" },
    ],
  },
  {
    id: "cw-25",
    rows: 13,
    cols: 13,
    grid: [
      [null, "F", null, null, null, null, null, null, null, null, null, null, null],
      ["K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S", null, null],
      [null, "U", null, null, "O", null, null, null, null, null, null, null, null],
      [null, "E", null, "G", "E", "S", "C", "H", "E", "N", "K", null, null],
      [null, "H", null, null, "N", null, "O", null, null, null, null, null, null],
      [null, "L", null, null, "I", null, "M", null, null, null, null, "G", null],
      [null, "I", null, null, "G", null, "P", "I", "N", "G", "U", "I", "N"],
      [null, "N", null, null, "I", null, "U", null, null, null, null, "T", null],
      [null, "G", null, null, "N", null, "T", null, "S", "A", "L", "A", "T"],
      [null, null, "B", null, null, null, "E", null, null, null, null, "R", null],
      ["K", "L", "A", "V", "I", "E", "R", null, null, null, null, "R", null],
      [null, null, "L", null, null, null, null, "W", "A", "S", "S", "E", "R"],
      [null, null, "L", null, null, null, null, null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 1, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 2, dir: "across", row: 1, col: 0, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 3, dir: "down", row: 1, col: 4, answer: "KOENIGIN", clue: "Weibliche Herrscherin" },
      { number: 4, dir: "across", row: 3, col: 3, answer: "GESCHENK", clue: "Wird zum Geburtstag überreicht" },
      { number: 5, dir: "down", row: 3, col: 6, answer: "COMPUTER", clue: "Elektronisches Rechengerät" },
      { number: 6, dir: "down", row: 5, col: 11, answer: "GITARRE", clue: "Saiteninstrument zum Zupfen" },
      { number: 7, dir: "across", row: 6, col: 6, answer: "PINGUIN", clue: "Flugunfähiger Vogel der Antarktis" },
      { number: 8, dir: "across", row: 8, col: 8, answer: "SALAT", clue: "Grünes, frisches Gericht" },
      { number: 9, dir: "down", row: 9, col: 2, answer: "BALL", clue: "Rundes Sportgerät" },
      { number: 10, dir: "across", row: 10, col: 0, answer: "KLAVIER", clue: "Tasteninstrument mit vielen Tönen" },
      { number: 11, dir: "across", row: 11, col: 7, answer: "WASSER", clue: "Lebensnotwendige, farblose Flüssigkeit" },
    ],
  },
  {
    id: "cw-26",
    rows: 13,
    cols: 13,
    grid: [
      ["R", "E", "I", "S", null, null, null, "K", "A", "R", "T", "E", null],
      [null, "N", null, null, null, null, null, "A", null, null, null, null, "P"],
      [null, "T", null, "F", null, null, null, "E", null, null, "Z", null, "O"],
      ["M", "E", "E", "R", null, "F", "U", "S", "S", "B", "A", "L", "L"],
      [null, null, null, "O", null, null, null, "E", null, null, "U", null, "I"],
      [null, "B", null, "S", null, null, null, null, "K", null, "B", null, "Z"],
      ["B", "A", "E", "C", "K", "E", "R", null, "A", null, "E", null, "E"],
      [null, "H", null, "H", null, null, null, null, "P", null, "R", null, "I"],
      [null, "N", null, null, null, null, null, null, "I", null, "E", null, null],
      [null, "H", null, "C", "O", "M", "P", "U", "T", "E", "R", null, null],
      [null, "O", null, null, null, null, null, null, "A", null, null, null, null],
      [null, "F", "L", "U", "G", "H", "A", "F", "E", "N", null, null, null],
      [null, null, null, null, null, null, null, null, "N", null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 0, answer: "REIS", clue: "Kleines weißes Getreidekorn als Beilage" },
      { number: 2, dir: "down", row: 0, col: 1, answer: "ENTE", clue: "Watschelt und quakt am Teich" },
      { number: 3, dir: "across", row: 0, col: 7, answer: "KARTE", clue: "Zeigt Länder oder wird beim Spielen benutzt" },
      { number: 3, dir: "down", row: 0, col: 7, answer: "KAESE", clue: "Aus Milch hergestellt, viele Sorten" },
      { number: 4, dir: "down", row: 1, col: 12, answer: "POLIZEI", clue: "Sorgt für Sicherheit und Ordnung" },
      { number: 5, dir: "down", row: 2, col: 3, answer: "FROSCH", clue: "Springt und quakt am Teich" },
      { number: 6, dir: "down", row: 2, col: 10, answer: "ZAUBERER", clue: "Wirkt in Märchen mit Magie" },
      { number: 7, dir: "across", row: 3, col: 0, answer: "MEER", clue: "Große, salzige Wassermasse" },
      { number: 8, dir: "across", row: 3, col: 5, answer: "FUSSBALL", clue: "Meistgespielte Ballsportart der Welt" },
      { number: 9, dir: "down", row: 5, col: 1, answer: "BAHNHOF", clue: "Wo Züge abfahren" },
      { number: 10, dir: "down", row: 5, col: 8, answer: "KAPITAEN", clue: "Führt ein Schiff" },
      { number: 11, dir: "across", row: 6, col: 0, answer: "BAECKER", clue: "Backt Brot und Brötchen" },
      { number: 12, dir: "across", row: 9, col: 3, answer: "COMPUTER", clue: "Elektronisches Rechengerät" },
      { number: 13, dir: "across", row: 11, col: 1, answer: "FLUGHAFEN", clue: "Wo Flugzeuge starten" },
    ],
  },
  {
    id: "cw-27",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, "T", null, null, "F", null, null, "N", null, null, null],
      [null, "K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S", null],
      [null, null, null, "X", null, null, "U", null, null, "C", null, null, null],
      ["K", "A", "P", "I", "T", "A", "E", "N", null, "H", null, null, null],
      [null, null, null, null, null, null, "R", null, null, "T", null, null, "Z"],
      [null, null, null, null, null, null, "W", null, null, null, "K", null, "W"],
      [null, "G", "E", "S", "C", "H", "E", "N", "K", null, "O", null, "I"],
      [null, "I", null, null, null, null, "H", null, null, null, "E", null, "E"],
      [null, "T", null, "M", "A", "E", "R", "C", "H", "E", "N", null, "B"],
      [null, "A", null, "A", null, null, null, null, null, null, "I", null, "E"],
      [null, "R", null, "U", null, null, "S", "P", "I", "E", "G", "E", "L"],
      [null, "R", null, "S", null, null, null, null, null, null, "I", null, null],
      [null, "E", null, null, "P", "I", "N", "G", "U", "I", "N", null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 3, answer: "TAXI", clue: "Mietwagen mit Fahrer" },
      { number: 2, dir: "down", row: 0, col: 6, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 3, dir: "down", row: 0, col: 9, answer: "NACHT", clue: "Dunkle Tageszeit" },
      { number: 4, dir: "across", row: 1, col: 1, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 5, dir: "across", row: 3, col: 0, answer: "KAPITAEN", clue: "Führt ein Schiff" },
      { number: 6, dir: "down", row: 4, col: 12, answer: "ZWIEBEL", clue: "Macht beim Schneiden die Augen tränen" },
      { number: 7, dir: "down", row: 5, col: 10, answer: "KOENIGIN", clue: "Weibliche Herrscherin" },
      { number: 8, dir: "across", row: 6, col: 1, answer: "GESCHENK", clue: "Wird zum Geburtstag überreicht" },
      { number: 8, dir: "down", row: 6, col: 1, answer: "GITARRE", clue: "Saiteninstrument zum Zupfen" },
      { number: 9, dir: "across", row: 8, col: 3, answer: "MAERCHEN", clue: "Fantastische Erzählung für Kinder" },
      { number: 9, dir: "down", row: 8, col: 3, answer: "MAUS", clue: "Kleines Nagetier, das Katzen jagen" },
      { number: 10, dir: "across", row: 10, col: 6, answer: "SPIEGEL", clue: "Zeigt das eigene Bild" },
      { number: 11, dir: "across", row: 12, col: 4, answer: "PINGUIN", clue: "Flugunfähiger Vogel der Antarktis" },
    ],
  },
  {
    id: "cw-28",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, "W", null, "M", null, null, "W"],
      [null, null, null, null, null, null, "M", "A", "L", "E", "R", "E", "I"],
      [null, "F", null, null, null, "F", null, "S", null, "D", null, null, "N"],
      [null, "L", null, "F", "L", "U", "S", "S", null, "A", null, null, "T"],
      [null, "U", null, null, null, "S", null, "E", null, "I", null, null, "E"],
      [null, "G", null, "F", null, "S", null, "R", null, "L", null, null, "R"],
      [null, "Z", null, "A", null, "B", null, null, null, "L", null, null, null],
      ["W", "E", "I", "H", "N", "A", "C", "H", "T", "E", "N", null, null],
      [null, "U", null, "R", null, "L", null, null, null, null, "E", "I", "S"],
      [null, "G", null, "R", null, "L", null, "M", null, null, "B", null, null],
      [null, null, null, "A", null, null, "L", "O", "E", "W", "E", null, null],
      [null, "E", "R", "D", "E", null, null, "N", null, null, "L", null, null],
      [null, null, null, null, null, null, null, "D", null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 7, answer: "WASSER", clue: "Lebensnotwendige, farblose Flüssigkeit" },
      { number: 2, dir: "down", row: 0, col: 9, answer: "MEDAILLE", clue: "Auszeichnung für Sportler:innen" },
      { number: 3, dir: "down", row: 0, col: 12, answer: "WINTER", clue: "Kälteste Jahreszeit" },
      { number: 4, dir: "across", row: 1, col: 6, answer: "MALEREI", clue: "Kunst mit Pinsel und Farbe" },
      { number: 5, dir: "down", row: 2, col: 1, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
      { number: 6, dir: "down", row: 2, col: 5, answer: "FUSSBALL", clue: "Meistgespielte Ballsportart der Welt" },
      { number: 7, dir: "across", row: 3, col: 3, answer: "FLUSS", clue: "Fließendes Gewässer" },
      { number: 8, dir: "down", row: 5, col: 3, answer: "FAHRRAD", clue: "Zweirädriges Fahrzeug ohne Motor" },
      { number: 9, dir: "across", row: 7, col: 0, answer: "WEIHNACHTEN", clue: "Fest im Dezember mit Geschenken" },
      { number: 10, dir: "down", row: 7, col: 10, answer: "NEBEL", clue: "Trübt die Sicht am Morgen" },
      { number: 11, dir: "across", row: 8, col: 10, answer: "EIS", clue: "Gefrorenes Wasser" },
      { number: 12, dir: "down", row: 9, col: 7, answer: "MOND", clue: "Umkreist die Erde, wechselt seine Phasen" },
      { number: 13, dir: "across", row: 10, col: 6, answer: "LOEWE", clue: "König der Tiere" },
      { number: 14, dir: "across", row: 11, col: 1, answer: "ERDE", clue: "Unser Heimatplanet" },
    ],
  },
  {
    id: "cw-29",
    rows: 13,
    cols: 13,
    grid: [
      ["R", "O", "S", "E", null, "I", null, null, null, "K", null, null, null],
      [null, null, "C", null, "K", "N", "O", "B", "L", "A", "U", "C", "H"],
      ["J", "A", "H", "R", null, "T", null, null, null, "E", null, "O", null],
      [null, null, "L", null, null, "E", null, null, null, "N", null, "M", null],
      [null, "M", "A", "L", "E", "R", "E", "I", null, "G", null, "P", null],
      [null, null, "F", null, null, "N", null, null, null, "U", null, "U", null],
      [null, null, null, "B", "A", "E", "C", "K", "E", "R", null, "T", null],
      [null, null, null, null, null, "T", null, "O", null, "U", null, "E", null],
      [null, null, null, null, "A", null, null, "E", null, null, null, "R", null],
      [null, null, null, null, "P", "R", "I", "N", "Z", null, null, null, null],
      [null, null, null, null, "F", null, null, "I", null, null, null, null, null],
      [null, null, null, null, "E", null, null, "G", "L", "U", "E", "C", "K"],
      [null, null, "M", "I", "L", "C", "H", null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 0, answer: "ROSE", clue: "Blume mit Dornen, Symbol der Liebe" },
      { number: 2, dir: "down", row: 0, col: 2, answer: "SCHLAF", clue: "Nächtliche Erholung" },
      { number: 3, dir: "down", row: 0, col: 5, answer: "INTERNET", clue: "Weltweites Datennetz" },
      { number: 4, dir: "down", row: 0, col: 9, answer: "KAENGURU", clue: "Australisches Beuteltier" },
      { number: 5, dir: "across", row: 1, col: 4, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 6, dir: "down", row: 1, col: 11, answer: "COMPUTER", clue: "Elektronisches Rechengerät" },
      { number: 7, dir: "across", row: 2, col: 0, answer: "JAHR", clue: "Zwölf Monate" },
      { number: 8, dir: "across", row: 4, col: 1, answer: "MALEREI", clue: "Kunst mit Pinsel und Farbe" },
      { number: 9, dir: "across", row: 6, col: 3, answer: "BAECKER", clue: "Backt Brot und Brötchen" },
      { number: 10, dir: "down", row: 6, col: 7, answer: "KOENIG", clue: "Herrscher eines Königreichs" },
      { number: 11, dir: "down", row: 8, col: 4, answer: "APFEL", clue: "Rundes Obst, hält den Doktor fern" },
      { number: 12, dir: "across", row: 9, col: 4, answer: "PRINZ", clue: "Sohn eines Königs" },
      { number: 13, dir: "across", row: 11, col: 7, answer: "GLUECK", clue: "Positives Gefühl der Zufriedenheit" },
      { number: 14, dir: "across", row: 12, col: 2, answer: "MILCH", clue: "Weißes Getränk aus dem Kuhstall" },
    ],
  },
  {
    id: "cw-30",
    rows: 13,
    cols: 13,
    grid: [
      [null, "S", null, null, null, null, null, null, null, null, null, null, null],
      ["S", "C", "H", "W", "I", "M", "M", "E", "N", null, null, "W", null],
      [null, "H", null, null, null, null, null, null, null, "E", null, "A", null],
      ["F", "L", "U", "G", "Z", "E", "U", "G", null, "L", null, "L", null],
      [null, "A", null, null, null, null, null, "I", null, "E", "R", "D", "E"],
      ["I", "N", "T", "E", "R", "N", "E", "T", null, "F", null, null, null],
      [null, "G", null, null, null, null, null, "A", null, "A", null, null, null],
      [null, "E", null, null, "Z", "I", "T", "R", "O", "N", "E", null, null],
      ["P", null, "S", null, null, null, null, "R", null, "T", null, null, null],
      ["I", null, "T", "H", "E", "A", "T", "E", "R", null, null, null, null],
      ["Z", null, "U", null, null, null, null, null, null, null, null, null, null],
      ["Z", null, "H", null, null, null, null, null, null, null, null, null, null],
      ["A", "D", "L", "E", "R", null, null, null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 1, answer: "SCHLANGE", clue: "Beinloses Reptil" },
      { number: 2, dir: "across", row: 1, col: 0, answer: "SCHWIMMEN", clue: "Sportliche Fortbewegung im Wasser" },
      { number: 3, dir: "down", row: 1, col: 11, answer: "WALD", clue: "Viele Bäume zusammen" },
      { number: 4, dir: "down", row: 2, col: 9, answer: "ELEFANT", clue: "Größtes Landsäugetier" },
      { number: 5, dir: "across", row: 3, col: 0, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
      { number: 6, dir: "down", row: 3, col: 7, answer: "GITARRE", clue: "Saiteninstrument zum Zupfen" },
      { number: 7, dir: "across", row: 4, col: 9, answer: "ERDE", clue: "Unser Heimatplanet" },
      { number: 8, dir: "across", row: 5, col: 0, answer: "INTERNET", clue: "Weltweites Datennetz" },
      { number: 9, dir: "across", row: 7, col: 4, answer: "ZITRONE", clue: "Saure gelbe Frucht" },
      { number: 10, dir: "down", row: 8, col: 0, answer: "PIZZA", clue: "Italienisches Fladengericht mit Belag" },
      { number: 11, dir: "down", row: 8, col: 2, answer: "STUHL", clue: "Möbelstück zum Sitzen" },
      { number: 12, dir: "across", row: 9, col: 2, answer: "THEATER", clue: "Ort für Bühnenstücke" },
      { number: 13, dir: "across", row: 12, col: 0, answer: "ADLER", clue: "Greifvogel, Wappentier Deutschlands" },
    ],
  },
  {
    id: "cw-31",
    rows: 12,
    cols: 13,
    grid: [
      [null, null, "G", "E", "S", "C", "H", "E", "N", "K", null, null, "W"],
      [null, null, null, null, null, null, null, null, null, "A", null, null, "O"],
      [null, "B", "I", "L", "D", "S", "C", "H", "I", "R", "M", null, "C"],
      [null, null, null, null, null, null, null, null, null, "T", null, null, "H"],
      ["F", "A", "M", "I", "L", "I", "E", null, "W", "O", "L", "K", "E"],
      [null, "R", null, null, null, "N", null, null, null, "F", null, null, null],
      [null, "Z", null, null, null, "T", null, null, null, "F", null, null, null],
      [null, "T", null, "M", "A", "E", "R", "C", "H", "E", "N", null, null],
      [null, null, null, null, null, "R", null, null, null, "L", null, null, null],
      [null, "K", "A", "L", "E", "N", "D", "E", "R", null, null, null, null],
      [null, null, null, null, null, "E", null, null, null, null, null, null, null],
      ["C", "O", "M", "P", "U", "T", "E", "R", null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 2, answer: "GESCHENK", clue: "Wird zum Geburtstag überreicht" },
      { number: 2, dir: "down", row: 0, col: 9, answer: "KARTOFFEL", clue: "Knolle, wird gekocht oder frittiert" },
      { number: 3, dir: "down", row: 0, col: 12, answer: "WOCHE", clue: "Sieben Tage" },
      { number: 4, dir: "across", row: 2, col: 1, answer: "BILDSCHIRM", clue: "Zeigt Inhalte am Computer an" },
      { number: 5, dir: "across", row: 4, col: 0, answer: "FAMILIE", clue: "Eltern, Kinder und Verwandte" },
      { number: 6, dir: "down", row: 4, col: 1, answer: "ARZT", clue: "Behandelt Kranke" },
      { number: 7, dir: "down", row: 4, col: 5, answer: "INTERNET", clue: "Weltweites Datennetz" },
      { number: 8, dir: "across", row: 4, col: 8, answer: "WOLKE", clue: "Schwebt am Himmel, bringt Regen" },
      { number: 9, dir: "across", row: 7, col: 3, answer: "MAERCHEN", clue: "Fantastische Erzählung für Kinder" },
      { number: 10, dir: "across", row: 9, col: 1, answer: "KALENDER", clue: "Zeigt Tage und Monate an" },
      { number: 11, dir: "across", row: 11, col: 0, answer: "COMPUTER", clue: "Elektronisches Rechengerät" },
    ],
  },
  {
    id: "cw-32",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, "R", "E", "G", "E", "N", null, null, null, null, null],
      [null, null, null, null, null, "U", null, null, null, null, null, null, null],
      ["K", "O", "F", "F", "E", "R", null, "C", null, null, null, "F", null],
      [null, null, null, "I", null, "K", null, "O", null, null, null, "L", null],
      [null, null, null, "S", null, "E", null, "M", null, null, null, "U", null],
      ["S", null, null, "C", null, null, null, "P", null, null, null, "G", null],
      ["C", null, null, "H", null, "F", "L", "U", "S", "S", null, "Z", null],
      ["H", null, null, "E", null, "E", null, "T", null, "C", null, "E", null],
      ["A", null, "K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S"],
      ["C", null, null, null, null, "S", null, "R", null, "L", null, "G", null],
      ["H", "E", "R", "B", "S", "T", null, null, null, "O", null, null, null],
      [null, null, null, null, null, "E", null, null, null, "S", null, null, null],
      ["K", "E", "L", "L", "E", "R", null, "W", "A", "S", "S", "E", "R"],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 3, answer: "REGEN", clue: "Fällt aus Wolken" },
      { number: 2, dir: "down", row: 0, col: 5, answer: "GURKE", clue: "Grünes, längliches Gemüse" },
      { number: 3, dir: "across", row: 2, col: 0, answer: "KOFFER", clue: "Für die Reise gepackt" },
      { number: 4, dir: "down", row: 2, col: 3, answer: "FISCHER", clue: "Fängt Fische zum Beruf" },
      { number: 5, dir: "down", row: 2, col: 7, answer: "COMPUTER", clue: "Elektronisches Rechengerät" },
      { number: 6, dir: "down", row: 2, col: 11, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
      { number: 7, dir: "down", row: 5, col: 0, answer: "SCHACH", clue: "Strategisches Brettspiel mit König und Dame" },
      { number: 8, dir: "across", row: 6, col: 5, answer: "FLUSS", clue: "Fließendes Gewässer" },
      { number: 8, dir: "down", row: 6, col: 5, answer: "FENSTER", clue: "Durchsichtige Öffnung in der Wand" },
      { number: 9, dir: "down", row: 6, col: 9, answer: "SCHLOSS", clue: "Prunkvolles Adelsgebäude" },
      { number: 10, dir: "across", row: 8, col: 2, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 11, dir: "across", row: 10, col: 0, answer: "HERBST", clue: "Jahreszeit mit buntem Laub" },
      { number: 12, dir: "across", row: 12, col: 0, answer: "KELLER", clue: "Unterster Raum eines Hauses" },
      { number: 13, dir: "across", row: 12, col: 7, answer: "WASSER", clue: "Lebensnotwendige, farblose Flüssigkeit" },
    ],
  },
];
