/**
 * Vorgenerierte Kreuzworträtsel-Gitter -- erzeugt von scripts/generate-crosswords.js
 * aus scripts/crossword-wordbank.js. Nicht von Hand bearbeiten; bei Bedarf
 * das Skript erneut laufen lassen (überschreibt diese Datei komplett).
 *
 * Auswahl pro Runde läuft wie beim Wissens-Quiz über pickUnseen() (siehe
 * content/crossword.ts) -- kein Wiederholen, solange der Pool nicht
 * ausgeschöpft ist, kontogebunden bzw. geräte-lokal für Gäste.
 */

export interface CrosswordEntry {
  number: number;
  dir: "across" | "down";
  row: number;
  col: number;
  answer: string;
  clue: string;
}

export interface CrosswordPuzzle {
  id: string;
  rows: number;
  cols: number;
  /** null = schwarze/leere Zelle, sonst der Buchstabe an dieser Stelle. */
  grid: (string | null)[][];
  entries: CrosswordEntry[];
}

export const crosswordPuzzles: CrosswordPuzzle[] = [
  {
    id: "cw-01",
    rows: 13,
    cols: 12,
    grid: [
      ["B", "U", "T", "T", "E", "R", null, null, null, null, null, null],
      ["A", null, null, null, null, null, "L", "U", "F", "T", null, null],
      ["H", null, null, "A", "U", "T", "O", null, null, null, "W", null],
      ["N", null, "K", null, null, null, "E", null, "F", null, "U", null],
      ["H", null, "O", null, null, "Z", "W", "I", "E", "B", "E", "L"],
      ["O", null, "E", null, null, null, "E", null, "U", null, "S", null],
      ["F", "E", "N", "S", "T", "E", "R", null, "E", null, "T", null],
      [null, null, "I", null, null, null, null, "B", "R", "I", "E", "F"],
      ["F", null, "G", null, null, null, null, null, "W", null, null, null],
      ["A", null, "I", "N", "T", "E", "R", "N", "E", "T", null, null],
      ["R", null, "N", null, null, null, null, null, "H", null, null, null],
      ["B", "I", "L", "D", "S", "C", "H", "I", "R", "M", null, null],
      ["E", null, null, null, null, null, null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 0, answer: "BUTTER", clue: "Streichfett aus Milch" },
      { number: 1, dir: "down", row: 0, col: 0, answer: "BAHNHOF", clue: "Wo Züge abfahren" },
      { number: 2, dir: "across", row: 1, col: 6, answer: "LUFT", clue: "Zum Atmen nötiges Gas-Gemisch" },
      { number: 2, dir: "down", row: 1, col: 6, answer: "LOEWE", clue: "König der Tiere" },
      { number: 3, dir: "across", row: 2, col: 3, answer: "AUTO", clue: "Vierrädriges Fahrzeug" },
      { number: 4, dir: "down", row: 2, col: 10, answer: "WUESTE", clue: "Sehr trockenes Gebiet voller Sand" },
      { number: 5, dir: "down", row: 3, col: 2, answer: "KOENIGIN", clue: "Weibliche Herrscherin" },
      { number: 6, dir: "down", row: 3, col: 8, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 7, dir: "across", row: 4, col: 5, answer: "ZWIEBEL", clue: "Macht beim Schneiden die Augen tränen" },
      { number: 8, dir: "across", row: 6, col: 0, answer: "FENSTER", clue: "Durchsichtige Öffnung in der Wand" },
      { number: 9, dir: "across", row: 7, col: 7, answer: "BRIEF", clue: "Schriftliche Nachricht per Post" },
      { number: 10, dir: "down", row: 8, col: 0, answer: "FARBE", clue: "Macht Bilder bunt" },
      { number: 11, dir: "across", row: 9, col: 2, answer: "INTERNET", clue: "Weltweites Datennetz" },
      { number: 12, dir: "across", row: 11, col: 0, answer: "BILDSCHIRM", clue: "Zeigt Inhalte am Computer an" },
    ],
  },
  {
    id: "cw-02",
    rows: 13,
    cols: 13,
    grid: [
      ["B", "U", "S", null, null, "A", null, null, null, null, "K", null, "O"],
      ["E", null, null, null, null, "U", null, "F", null, null, "O", null, "R"],
      ["T", "A", "S", "T", "A", "T", "U", "R", null, null, "E", null, "A"],
      ["T", null, "C", null, null, "O", null, "U", null, null, "N", null, "N"],
      ["S", "C", "H", "M", "E", "T", "T", "E", "R", "L", "I", "N", "G"],
      ["C", null, "O", null, null, null, null, "H", null, null, "G", null, "E"],
      ["H", null, "K", null, "S", "C", "H", "L", "A", "N", "G", "E", null],
      ["W", null, "O", null, null, null, null, "I", null, null, null, null, null],
      ["I", null, "L", null, "K", "O", "E", "N", "I", "G", "I", "N", null],
      ["M", null, "A", null, null, null, null, "G", null, null, null, null, null],
      ["M", null, "D", null, null, null, null, null, null, null, null, null, null],
      ["E", "L", "E", "F", "A", "N", "T", null, null, null, null, null, null],
      ["N", null, null, null, null, null, null, null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 0, answer: "BUS", clue: "Öffentliches Fahrzeug für viele Personen" },
      { number: 1, dir: "down", row: 0, col: 0, answer: "BETT", clue: "Möbelstück zum Schlafen" },
      { number: 2, dir: "down", row: 0, col: 5, answer: "AUTO", clue: "Vierrädriges Fahrzeug" },
      { number: 3, dir: "down", row: 0, col: 10, answer: "KOENIG", clue: "Herrscher eines Königreichs" },
      { number: 4, dir: "down", row: 0, col: 12, answer: "ORANGE", clue: "Runde Zitrusfrucht" },
      { number: 5, dir: "down", row: 1, col: 7, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 6, dir: "across", row: 2, col: 0, answer: "TASTATUR", clue: "Zum Tippen am Computer" },
      { number: 7, dir: "down", row: 2, col: 2, answer: "SCHOKOLADE", clue: "Süße Nascherei aus Kakao" },
      { number: 8, dir: "across", row: 4, col: 0, answer: "SCHMETTERLING", clue: "Bunt geflügeltes Insekt" },
      { number: 8, dir: "down", row: 4, col: 0, answer: "SCHWIMMEN", clue: "Sportliche Fortbewegung im Wasser" },
      { number: 9, dir: "across", row: 6, col: 4, answer: "SCHLANGE", clue: "Beinloses Reptil" },
      { number: 10, dir: "across", row: 8, col: 4, answer: "KOENIGIN", clue: "Weibliche Herrscherin" },
      { number: 11, dir: "across", row: 11, col: 0, answer: "ELEFANT", clue: "Größtes Landsäugetier" },
    ],
  },
  {
    id: "cw-03",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, "L", "I", "E", "B", "E", null],
      [null, null, null, "J", "A", "H", "R", null, null, null, "A", null, null],
      [null, "K", null, null, "F", null, null, "S", "C", "H", "N", "E", "E"],
      [null, "N", null, null, "F", null, null, "C", null, null, "A", null, null],
      [null, "O", null, null, "E", null, null, "H", null, null, "N", null, "K"],
      [null, "B", null, null, "U", null, null, "W", null, null, "E", null, "O"],
      [null, "L", null, null, "E", null, null, "I", null, "S", null, null, "E"],
      ["M", "A", "L", "E", "R", null, null, "M", null, "C", null, null, "N"],
      [null, "U", null, null, "W", null, null, "M", null, "H", null, null, "I"],
      ["S", "C", "H", "M", "E", "T", "T", "E", "R", "L", "I", "N", "G"],
      [null, "H", null, null, "H", null, null, "N", null, "O", null, null, "I"],
      [null, null, null, null, "R", null, null, null, null, "S", null, null, "N"],
      [null, null, null, null, null, "A", "M", "E", "I", "S", "E", null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 7, answer: "LIEBE", clue: "Starkes, warmes Gefühl für jemanden" },
      { number: 2, dir: "down", row: 0, col: 10, answer: "BANANE", clue: "Gelbes, krummes Obst" },
      { number: 3, dir: "across", row: 1, col: 3, answer: "JAHR", clue: "Zwölf Monate" },
      { number: 4, dir: "down", row: 1, col: 4, answer: "AFFE", clue: "Kletternder Verwandter des Menschen" },
      { number: 5, dir: "down", row: 2, col: 1, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 6, dir: "across", row: 2, col: 7, answer: "SCHNEE", clue: "Weiße Winterflocken" },
      { number: 6, dir: "down", row: 2, col: 7, answer: "SCHWIMMEN", clue: "Sportliche Fortbewegung im Wasser" },
      { number: 7, dir: "down", row: 3, col: 4, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 8, dir: "down", row: 4, col: 12, answer: "KOENIGIN", clue: "Weibliche Herrscherin" },
      { number: 9, dir: "down", row: 6, col: 9, answer: "SCHLOSS", clue: "Prunkvolles Adelsgebäude" },
      { number: 10, dir: "across", row: 7, col: 0, answer: "MALER", clue: "Streicht Wände oder malt Bilder" },
      { number: 11, dir: "across", row: 9, col: 0, answer: "SCHMETTERLING", clue: "Bunt geflügeltes Insekt" },
      { number: 12, dir: "across", row: 12, col: 5, answer: "AMEISE", clue: "Fleißiges Insekt im Staat" },
    ],
  },
  {
    id: "cw-04",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, "T", "R", "A", "U", "M", null],
      [null, null, null, null, null, null, null, null, null, "B", null, null, null],
      [null, null, null, null, "K", null, null, "F", "R", "E", "U", "N", "D"],
      ["B", null, "K", null, "R", null, null, "L", null, "N", null, null, null],
      ["I", null, "I", null, "A", null, null, "U", null, "D", null, "K", null],
      ["L", null, "R", null, "N", null, null, "G", null, "U", null, "A", null],
      ["D", null, "C", null, "K", null, null, "Z", null, "R", null, "E", null],
      ["S", "C", "H", "M", "E", "T", "T", "E", "R", "L", "I", "N", "G"],
      ["C", null, "E", null, "N", null, null, "U", null, "A", null, "G", null],
      ["H", null, null, null, "H", null, null, "G", null, "U", null, "U", null],
      ["I", null, "S", "P", "A", "T", "Z", null, null, "B", "E", "R", "G"],
      ["R", null, null, null, "U", null, null, null, null, null, null, "U", null],
      ["M", null, null, null, "S", "C", "H", "A", "C", "H", null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 7, answer: "TRAUM", clue: "Erlebnis während des Schlafs" },
      { number: 2, dir: "down", row: 0, col: 9, answer: "ABEND", clue: "Übergang zur Nacht" },
      { number: 3, dir: "down", row: 2, col: 4, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 4, dir: "across", row: 2, col: 7, answer: "FREUND", clue: "Enger, vertrauter Begleiter" },
      { number: 4, dir: "down", row: 2, col: 7, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
      { number: 5, dir: "down", row: 3, col: 0, answer: "BILDSCHIRM", clue: "Zeigt Inhalte am Computer an" },
      { number: 6, dir: "down", row: 3, col: 2, answer: "KIRCHE", clue: "Gebäude für Gottesdienste" },
      { number: 7, dir: "down", row: 4, col: 11, answer: "KAENGURU", clue: "Australisches Beuteltier" },
      { number: 8, dir: "down", row: 5, col: 9, answer: "URLAUB", clue: "Freie Zeit zum Erholen" },
      { number: 9, dir: "across", row: 7, col: 0, answer: "SCHMETTERLING", clue: "Bunt geflügeltes Insekt" },
      { number: 10, dir: "across", row: 10, col: 2, answer: "SPATZ", clue: "Kleiner, häufiger Stadtvogel" },
      { number: 11, dir: "across", row: 10, col: 9, answer: "BERG", clue: "Hohe Erhebung der Landschaft" },
      { number: 12, dir: "across", row: 12, col: 4, answer: "SCHACH", clue: "Strategisches Brettspiel mit König und Dame" },
    ],
  },
  {
    id: "cw-05",
    rows: 13,
    cols: 13,
    grid: [
      ["T", "R", "A", "I", "N", "E", "R", null, "G", null, null, null, null],
      [null, null, "P", null, null, null, null, "B", "L", "U", "M", "E", null],
      ["K", null, "O", null, null, null, null, null, "U", null, null, null, null],
      ["R", null, "T", null, "S", "T", "U", "D", "E", "N", "T", null, "G"],
      ["A", null, "H", null, "C", null, null, null, "C", null, "O", null, "E"],
      ["N", null, "E", null, "H", null, null, null, "K", null, "R", null, "B"],
      ["K", null, "K", "N", "O", "B", "L", "A", "U", "C", "H", null, "U"],
      ["E", null, "E", null, "K", null, null, null, null, null, null, null, "R"],
      ["N", null, null, null, "O", null, null, null, null, null, null, null, "T"],
      ["H", null, null, "F", "L", "U", "G", "Z", "E", "U", "G", null, "S"],
      ["A", null, null, null, "A", null, null, null, null, null, null, null, "T"],
      ["U", null, null, null, "D", null, null, null, null, null, null, null, "A"],
      ["S", "C", "H", "M", "E", "T", "T", "E", "R", "L", "I", "N", "G"],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 0, answer: "TRAINER", clue: "Leitet das Team beim Training" },
      { number: 2, dir: "down", row: 0, col: 2, answer: "APOTHEKE", clue: "Verkauft Medikamente" },
      { number: 3, dir: "down", row: 0, col: 8, answer: "GLUECK", clue: "Positives Gefühl der Zufriedenheit" },
      { number: 4, dir: "across", row: 1, col: 7, answer: "BLUME", clue: "Bunte, duftende Pflanze" },
      { number: 5, dir: "down", row: 2, col: 0, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 6, dir: "across", row: 3, col: 4, answer: "STUDENT", clue: "Lernt an der Universität" },
      { number: 6, dir: "down", row: 3, col: 4, answer: "SCHOKOLADE", clue: "Süße Nascherei aus Kakao" },
      { number: 7, dir: "down", row: 3, col: 10, answer: "TOR", clue: "Ziel beim Fußball" },
      { number: 8, dir: "down", row: 3, col: 12, answer: "GEBURTSTAG", clue: "Jährlicher Feiertag der eigenen Geburt" },
      { number: 9, dir: "across", row: 6, col: 2, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 10, dir: "across", row: 9, col: 3, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
      { number: 11, dir: "across", row: 12, col: 0, answer: "SCHMETTERLING", clue: "Bunt geflügeltes Insekt" },
    ],
  },
  {
    id: "cw-06",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, "M", "O", "R", "G", "E", "N", null, null],
      [null, null, null, null, null, "U", null, null, null, null, null, null, null],
      [null, null, null, null, null, "S", null, null, null, null, null, null, null],
      ["K", "L", "A", "V", "I", "E", "R", null, null, "B", null, "K", null],
      ["A", null, "P", null, null, "U", null, "F", null, "I", null, "N", null],
      ["F", null, "O", null, null, "M", null, "L", null, "L", null, "O", null],
      ["F", null, "T", null, null, "B", null, "U", null, "D", null, "B", null],
      ["E", null, "H", null, null, "A", null, "G", null, "S", null, "L", null],
      ["E", null, "E", null, null, "H", null, "Z", null, "C", null, "A", null],
      [null, null, "K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S"],
      [null, null, "E", null, null, "H", null, "U", null, "I", null, "C", null],
      [null, null, null, null, null, "O", null, "G", null, "R", null, "H", null],
      ["G", "I", "R", "A", "F", "F", "E", null, null, "M", null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 5, answer: "MORGEN", clue: "Beginn des Tages" },
      { number: 1, dir: "down", row: 0, col: 5, answer: "MUSEUM", clue: "Ort für Kunst und Ausstellungen" },
      { number: 2, dir: "across", row: 3, col: 0, answer: "KLAVIER", clue: "Tasteninstrument mit vielen Tönen" },
      { number: 2, dir: "down", row: 3, col: 0, answer: "KAFFEE", clue: "Koffeinhaltiges, warmes Getränk" },
      { number: 3, dir: "down", row: 3, col: 2, answer: "APOTHEKE", clue: "Verkauft Medikamente" },
      { number: 4, dir: "down", row: 3, col: 9, answer: "BILDSCHIRM", clue: "Zeigt Inhalte am Computer an" },
      { number: 5, dir: "down", row: 3, col: 11, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 6, dir: "down", row: 4, col: 7, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
      { number: 7, dir: "down", row: 6, col: 5, answer: "BAHNHOF", clue: "Wo Züge abfahren" },
      { number: 8, dir: "across", row: 9, col: 2, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 9, dir: "across", row: 12, col: 0, answer: "GIRAFFE", clue: "Tier mit dem längsten Hals" },
    ],
  },
  {
    id: "cw-07",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, null, "S", null, null, null, null],
      [null, null, null, "M", "O", "N", "D", null, "A", null, null, null, null],
      [null, null, null, "U", null, null, null, null, "L", null, null, "F", null],
      [null, null, null, "S", null, null, "F", null, "Z", null, null, "E", null],
      [null, "K", null, "I", null, null, "E", null, "A", "B", "E", "N", "D"],
      ["W", "O", "L", "K", "E", null, "U", null, "U", null, null, "S", null],
      [null, "E", null, "R", null, null, "E", null, "B", null, null, "T", null],
      [null, "N", null, "O", null, "B", "R", "U", "E", "C", "K", "E", null],
      [null, "I", null, "K", null, null, "W", null, "R", null, null, "R", null],
      [null, "G", null, "O", null, null, "E", null, "E", null, null, null, null],
      ["B", "I", "L", "D", "S", "C", "H", "I", "R", "M", null, null, null],
      [null, "N", null, "I", null, null, "R", null, null, null, null, null, null],
      [null, null, null, "L", null, null, null, null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 8, answer: "SALZ", clue: "Würzt fast jedes Gericht" },
      { number: 2, dir: "across", row: 1, col: 3, answer: "MOND", clue: "Umkreist die Erde, wechselt seine Phasen" },
      { number: 2, dir: "down", row: 1, col: 3, answer: "MUSIK", clue: "Klänge, die man hört und fühlt" },
      { number: 3, dir: "down", row: 2, col: 11, answer: "FENSTER", clue: "Durchsichtige Öffnung in der Wand" },
      { number: 4, dir: "down", row: 3, col: 6, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 5, dir: "down", row: 3, col: 8, answer: "ZAUBERER", clue: "Wirkt in Märchen mit Magie" },
      { number: 6, dir: "down", row: 4, col: 1, answer: "KOENIGIN", clue: "Weibliche Herrscherin" },
      { number: 7, dir: "across", row: 4, col: 8, answer: "ABEND", clue: "Übergang zur Nacht" },
      { number: 8, dir: "across", row: 5, col: 0, answer: "WOLKE", clue: "Schwebt am Himmel, bringt Regen" },
      { number: 9, dir: "down", row: 5, col: 3, answer: "KROKODIL", clue: "Reptil mit vielen scharfen Zähnen im Wasser" },
      { number: 10, dir: "across", row: 7, col: 5, answer: "BRUECKE", clue: "Führt über einen Fluss" },
      { number: 11, dir: "across", row: 10, col: 0, answer: "BILDSCHIRM", clue: "Zeigt Inhalte am Computer an" },
    ],
  },
  {
    id: "cw-08",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, "K", "A", "P", "I", "T", "A", "E", "N", null, null, null],
      [null, null, null, "F", null, "N", null, null, null, null, "T", null, null],
      [null, null, null, "F", null, "T", null, null, null, null, "U", null, null],
      [null, null, "F", "E", "U", "E", "R", "W", "E", "H", "R", null, null],
      [null, null, "U", null, null, "R", null, "O", null, null, "M", null, null],
      ["P", "A", "S", "S", null, "N", null, "L", null, "P", null, "K", null],
      [null, null, "S", null, null, "E", null, "F", null, "I", null, "A", null],
      [null, null, "B", null, null, "T", "R", "A", "I", "N", "E", "R", null],
      [null, null, "A", null, null, null, null, null, null, "G", null, "T", null],
      ["P", "I", "L", "O", "T", null, null, null, null, "U", null, "E", null],
      [null, null, "L", null, "A", null, "P", "O", "L", "I", "Z", "E", "I"],
      [null, null, null, null, "N", null, null, null, null, "N", null, null, null],
      [null, null, null, null, "Z", null, null, null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 2, answer: "KAPITAEN", clue: "Führt ein Schiff" },
      { number: 2, dir: "down", row: 0, col: 3, answer: "AFFE", clue: "Kletternder Verwandter des Menschen" },
      { number: 3, dir: "down", row: 0, col: 5, answer: "INTERNET", clue: "Weltweites Datennetz" },
      { number: 4, dir: "down", row: 1, col: 10, answer: "TURM", clue: "Hohes, schmales Bauwerk" },
      { number: 5, dir: "across", row: 3, col: 2, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 5, dir: "down", row: 3, col: 2, answer: "FUSSBALL", clue: "Meistgespielte Ballsportart der Welt" },
      { number: 6, dir: "down", row: 3, col: 7, answer: "WOLF", clue: "Wildes Rudeltier, Vorfahr des Hundes" },
      { number: 7, dir: "across", row: 5, col: 0, answer: "PASS", clue: "Wichtiges Reisedokument" },
      { number: 8, dir: "down", row: 5, col: 9, answer: "PINGUIN", clue: "Flugunfähiger Vogel der Antarktis" },
      { number: 9, dir: "down", row: 5, col: 11, answer: "KARTE", clue: "Zeigt Länder oder wird beim Spielen benutzt" },
      { number: 10, dir: "across", row: 7, col: 5, answer: "TRAINER", clue: "Leitet das Team beim Training" },
      { number: 11, dir: "across", row: 9, col: 0, answer: "PILOT", clue: "Steuert ein Flugzeug" },
      { number: 12, dir: "down", row: 9, col: 4, answer: "TANZ", clue: "Rhythmische Bewegung zur Musik" },
      { number: 13, dir: "across", row: 10, col: 6, answer: "POLIZEI", clue: "Sorgt für Sicherheit und Ordnung" },
    ],
  },
  {
    id: "cw-09",
    rows: 13,
    cols: 13,
    grid: [
      [null, "S", "T", "U", "D", "E", "N", "T", null, null, null, null, null],
      [null, null, null, null, null, null, null, "R", null, "M", null, null, null],
      ["V", "U", "L", "K", "A", "N", null, "A", null, "E", null, "F", null],
      [null, null, null, "L", null, null, null, "I", null, "D", null, "U", null],
      [null, "K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S", null],
      [null, "O", null, "V", null, "N", null, "E", null, "I", null, "S", null],
      [null, "E", null, "I", null, "O", null, "R", null, "L", null, "B", null],
      [null, "N", null, "E", null, "B", null, null, null, "L", null, "A", null],
      [null, "I", null, "R", null, "L", null, "D", null, "E", "U", "L", "E"],
      [null, "G", null, null, null, "A", null, "A", null, null, null, "L", null],
      [null, "I", null, "B", "R", "U", "E", "C", "K", "E", null, null, null],
      [null, "N", null, null, null, "C", null, "H", null, null, null, null, null],
      [null, null, null, "S", "C", "H", "L", "A", "N", "G", "E", null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 1, answer: "STUDENT", clue: "Lernt an der Universität" },
      { number: 2, dir: "down", row: 0, col: 7, answer: "TRAINER", clue: "Leitet das Team beim Training" },
      { number: 3, dir: "down", row: 1, col: 9, answer: "MEDAILLE", clue: "Auszeichnung für Sportler:innen" },
      { number: 4, dir: "across", row: 2, col: 0, answer: "VULKAN", clue: "Berg, der Lava spuckt" },
      { number: 5, dir: "down", row: 2, col: 3, answer: "KLAVIER", clue: "Tasteninstrument mit vielen Tönen" },
      { number: 6, dir: "down", row: 2, col: 11, answer: "FUSSBALL", clue: "Meistgespielte Ballsportart der Welt" },
      { number: 7, dir: "across", row: 4, col: 1, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 7, dir: "down", row: 4, col: 1, answer: "KOENIGIN", clue: "Weibliche Herrscherin" },
      { number: 8, dir: "down", row: 4, col: 5, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 9, dir: "down", row: 8, col: 7, answer: "DACH", clue: "Oberer Abschluss eines Hauses" },
      { number: 10, dir: "across", row: 8, col: 9, answer: "EULE", clue: "Nachtaktiver Vogel mit großen Augen" },
      { number: 11, dir: "across", row: 10, col: 3, answer: "BRUECKE", clue: "Führt über einen Fluss" },
      { number: 12, dir: "across", row: 12, col: 3, answer: "SCHLANGE", clue: "Beinloses Reptil" },
    ],
  },
  {
    id: "cw-10",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, null, "F", null, null, null, "T"],
      [null, null, null, null, "K", "L", "A", "V", "I", "E", "R", null, "R"],
      [null, "H", null, null, null, null, null, null, "S", null, null, null, "A"],
      ["T", "U", "E", "R", null, null, null, null, "C", null, null, null, "I"],
      [null, "N", null, null, "F", "L", "U", "G", "H", "A", "F", "E", "N"],
      ["A", "D", "L", "E", "R", null, null, null, "E", null, null, null, "E"],
      [null, null, null, null, "U", null, null, null, "R", null, null, null, "R"],
      [null, null, null, "F", "E", "U", "E", "R", "W", "E", "H", "R", null],
      [null, null, null, null, "H", null, "I", null, null, null, null, null, "M"],
      [null, null, null, null, "L", null, "S", null, null, null, null, null, "O"],
      [null, null, "W", "E", "I", "H", "N", "A", "C", "H", "T", "E", "N"],
      [null, null, null, null, "N", null, null, null, null, null, null, null, "A"],
      [null, null, null, null, "G", "I", "T", "A", "R", "R", "E", null, "T"],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 8, answer: "FISCHER", clue: "Fängt Fische zum Beruf" },
      { number: 2, dir: "down", row: 0, col: 12, answer: "TRAINER", clue: "Leitet das Team beim Training" },
      { number: 3, dir: "across", row: 1, col: 4, answer: "KLAVIER", clue: "Tasteninstrument mit vielen Tönen" },
      { number: 4, dir: "down", row: 2, col: 1, answer: "HUND", clue: "Bester Freund des Menschen" },
      { number: 5, dir: "across", row: 3, col: 0, answer: "TUER", clue: "Zum Öffnen und Schließen eines Raums" },
      { number: 6, dir: "across", row: 4, col: 4, answer: "FLUGHAFEN", clue: "Wo Flugzeuge starten" },
      { number: 6, dir: "down", row: 4, col: 4, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 7, dir: "across", row: 5, col: 0, answer: "ADLER", clue: "Greifvogel, Wappentier Deutschlands" },
      { number: 8, dir: "across", row: 7, col: 3, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 9, dir: "down", row: 7, col: 6, answer: "EIS", clue: "Gefrorenes Wasser" },
      { number: 10, dir: "down", row: 8, col: 12, answer: "MONAT", clue: "Etwa vier Wochen" },
      { number: 11, dir: "across", row: 10, col: 2, answer: "WEIHNACHTEN", clue: "Fest im Dezember mit Geschenken" },
      { number: 12, dir: "across", row: 12, col: 4, answer: "GITARRE", clue: "Saiteninstrument zum Zupfen" },
    ],
  },
  {
    id: "cw-11",
    rows: 13,
    cols: 13,
    grid: [
      ["F", null, null, null, null, null, "G", null, null, null, null, null, null],
      ["I", null, "S", "T", "A", "D", "I", "O", "N", null, null, null, null],
      ["L", null, null, null, null, null, "T", null, null, null, "C", null, null],
      ["M", null, null, null, null, "B", "A", "H", "N", "H", "O", "F", null],
      ["O", null, null, "F", null, null, "R", null, null, null, "M", null, "D"],
      ["N", "E", "B", "E", "L", null, "R", null, "D", null, "P", null, "O"],
      ["A", null, null, "U", null, null, "E", null, "A", null, "U", null, "N"],
      ["T", null, "W", "E", "I", "H", "N", "A", "C", "H", "T", "E", "N"],
      [null, "S", null, "R", null, null, null, null, "H", null, "E", null, "E"],
      [null, "T", null, "W", null, "Z", "A", "U", "B", "E", "R", "E", "R"],
      [null, "I", null, "E", null, null, null, null, null, null, null, null, null],
      [null, "F", "A", "H", "R", "R", "A", "D", null, null, null, null, null],
      [null, "T", null, "R", null, null, null, null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 0, answer: "FILM", clue: "Bewegte Bilder im Kino" },
      { number: 2, dir: "down", row: 0, col: 6, answer: "GITARRE", clue: "Saiteninstrument zum Zupfen" },
      { number: 3, dir: "across", row: 1, col: 2, answer: "STADION", clue: "Großer Sportaustragungsort" },
      { number: 4, dir: "down", row: 2, col: 10, answer: "COMPUTER", clue: "Elektronisches Rechengerät" },
      { number: 5, dir: "down", row: 3, col: 0, answer: "MONAT", clue: "Etwa vier Wochen" },
      { number: 6, dir: "across", row: 3, col: 5, answer: "BAHNHOF", clue: "Wo Züge abfahren" },
      { number: 7, dir: "down", row: 4, col: 3, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 8, dir: "down", row: 4, col: 12, answer: "DONNER", clue: "Grollt nach dem Blitz" },
      { number: 9, dir: "across", row: 5, col: 0, answer: "NEBEL", clue: "Trübt die Sicht am Morgen" },
      { number: 10, dir: "down", row: 5, col: 8, answer: "DACH", clue: "Oberer Abschluss eines Hauses" },
      { number: 11, dir: "across", row: 7, col: 2, answer: "WEIHNACHTEN", clue: "Fest im Dezember mit Geschenken" },
      { number: 12, dir: "down", row: 8, col: 1, answer: "STIFT", clue: "Zum Schreiben und Malen" },
      { number: 13, dir: "across", row: 9, col: 5, answer: "ZAUBERER", clue: "Wirkt in Märchen mit Magie" },
      { number: 14, dir: "across", row: 11, col: 1, answer: "FAHRRAD", clue: "Zweirädriges Fahrzeug ohne Motor" },
    ],
  },
  {
    id: "cw-12",
    rows: 13,
    cols: 13,
    grid: [
      [null, "F", "A", "H", "R", "R", "A", "D", null, "B", null, null, "M"],
      [null, null, null, null, null, null, "P", null, null, "I", null, null, "E"],
      [null, null, null, "S", "C", "H", "O", "K", "O", "L", "A", "D", "E"],
      [null, null, null, null, null, null, "T", null, null, "D", null, null, "R"],
      ["N", "A", "C", "H", "T", null, "H", null, null, "S", null, "F", null],
      ["E", null, null, null, "R", null, "E", null, null, "C", null, "R", null],
      ["B", null, "K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S"],
      ["E", null, "O", null, "U", null, "E", null, null, "I", null, "E", null],
      ["L", null, "N", null, "B", null, null, "K", "I", "R", "C", "H", "E"],
      [null, null, "Z", null, "E", null, null, null, null, "M", null, "L", null],
      [null, null, "E", "L", "E", "F", "A", "N", "T", null, null, "I", null],
      [null, null, "R", null, null, null, null, null, null, null, null, "N", null],
      [null, null, "T", null, "F", "L", "U", "G", "Z", "E", "U", "G", null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 1, answer: "FAHRRAD", clue: "Zweirädriges Fahrzeug ohne Motor" },
      { number: 2, dir: "down", row: 0, col: 6, answer: "APOTHEKE", clue: "Verkauft Medikamente" },
      { number: 3, dir: "down", row: 0, col: 9, answer: "BILDSCHIRM", clue: "Zeigt Inhalte am Computer an" },
      { number: 4, dir: "down", row: 0, col: 12, answer: "MEER", clue: "Große, salzige Wassermasse" },
      { number: 5, dir: "across", row: 2, col: 3, answer: "SCHOKOLADE", clue: "Süße Nascherei aus Kakao" },
      { number: 6, dir: "across", row: 4, col: 0, answer: "NACHT", clue: "Dunkle Tageszeit" },
      { number: 6, dir: "down", row: 4, col: 0, answer: "NEBEL", clue: "Trübt die Sicht am Morgen" },
      { number: 7, dir: "down", row: 4, col: 4, answer: "TRAUBE", clue: "Wird zu Wein verarbeitet" },
      { number: 8, dir: "down", row: 4, col: 11, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 9, dir: "across", row: 6, col: 2, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 9, dir: "down", row: 6, col: 2, answer: "KONZERT", clue: "Live-Musikveranstaltung" },
      { number: 10, dir: "across", row: 8, col: 7, answer: "KIRCHE", clue: "Gebäude für Gottesdienste" },
      { number: 11, dir: "across", row: 10, col: 2, answer: "ELEFANT", clue: "Größtes Landsäugetier" },
      { number: 12, dir: "across", row: 12, col: 4, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
    ],
  },
  {
    id: "cw-13",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, "K", "A", "F", "F", "E", "E", null, "G", null, null],
      [null, null, null, null, null, null, "L", null, null, null, "A", null, null],
      [null, null, null, null, null, null, "O", null, "F", "A", "R", "B", "E"],
      [null, null, null, null, null, null, "E", null, null, null, "T", null, null],
      [null, null, null, "K", "A", "R", "T", "O", "F", "F", "E", "L", null],
      [null, null, null, null, null, null, "E", null, "R", null, "N", null, null],
      [null, null, "T", "A", "S", "T", "A", "T", "U", "R", null, null, "S"],
      ["P", null, null, null, null, "H", null, null, "E", null, null, null, "C"],
      ["R", null, null, "M", "A", "E", "R", "C", "H", "E", "N", null, "H"],
      ["I", null, "R", null, null, "A", null, null, "L", null, null, null, "U"],
      ["N", null, "E", null, null, "T", null, "P", "I", "N", "S", "E", "L"],
      ["Z", "W", "I", "E", "B", "E", "L", null, "N", null, null, null, "E"],
      [null, null, "S", null, null, "R", null, null, "G", null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 3, answer: "KAFFEE", clue: "Koffeinhaltiges, warmes Getränk" },
      { number: 2, dir: "down", row: 0, col: 6, answer: "FLOETE", clue: "Wird geblasen, dünnes Rohr" },
      { number: 3, dir: "down", row: 0, col: 10, answer: "GARTEN", clue: "Grünfläche zum Anpflanzen" },
      { number: 4, dir: "across", row: 2, col: 8, answer: "FARBE", clue: "Macht Bilder bunt" },
      { number: 5, dir: "across", row: 4, col: 3, answer: "KARTOFFEL", clue: "Knolle, wird gekocht oder frittiert" },
      { number: 6, dir: "down", row: 4, col: 8, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 7, dir: "across", row: 6, col: 2, answer: "TASTATUR", clue: "Zum Tippen am Computer" },
      { number: 8, dir: "down", row: 6, col: 5, answer: "THEATER", clue: "Ort für Bühnenstücke" },
      { number: 9, dir: "down", row: 6, col: 12, answer: "SCHULE", clue: "Ort zum Lernen für Kinder" },
      { number: 10, dir: "down", row: 7, col: 0, answer: "PRINZ", clue: "Sohn eines Königs" },
      { number: 11, dir: "across", row: 8, col: 3, answer: "MAERCHEN", clue: "Fantastische Erzählung für Kinder" },
      { number: 12, dir: "down", row: 9, col: 2, answer: "REIS", clue: "Kleines weißes Getreidekorn als Beilage" },
      { number: 13, dir: "across", row: 10, col: 7, answer: "PINSEL", clue: "Werkzeug zum Malen" },
      { number: 14, dir: "across", row: 11, col: 0, answer: "ZWIEBEL", clue: "Macht beim Schneiden die Augen tränen" },
    ],
  },
  {
    id: "cw-14",
    rows: 13,
    cols: 13,
    grid: [
      [null, "B", "U", "S", null, null, null, null, null, null, null, null, null],
      [null, null, null, "C", null, "A", null, "S", "A", "F", "T", null, null],
      [null, null, null, "H", null, "P", null, "C", null, null, null, "I", null],
      [null, null, "A", "U", "T", "O", null, "H", null, "S", null, "N", null],
      [null, null, null, "L", null, "T", null, "L", null, "C", null, "T", null],
      [null, null, "W", "E", "I", "H", "N", "A", "C", "H", "T", "E", "N"],
      [null, null, "U", null, null, "E", null, "N", null, "O", null, "R", null],
      [null, null, "E", null, null, "K", null, "G", null, "K", null, "N", null],
      [null, null, "R", null, null, "E", null, "E", null, "O", null, "E", null],
      ["A", "F", "F", "E", null, null, null, null, null, "L", null, "T", null],
      [null, null, "E", null, "F", "L", "U", "G", "H", "A", "F", "E", "N"],
      ["T", "A", "L", null, null, null, null, null, null, "D", null, null, null],
      [null, null, "K", "A", "R", "T", "O", "F", "F", "E", "L", null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 1, answer: "BUS", clue: "Öffentliches Fahrzeug für viele Personen" },
      { number: 2, dir: "down", row: 0, col: 3, answer: "SCHULE", clue: "Ort zum Lernen für Kinder" },
      { number: 3, dir: "down", row: 1, col: 5, answer: "APOTHEKE", clue: "Verkauft Medikamente" },
      { number: 4, dir: "across", row: 1, col: 7, answer: "SAFT", clue: "Getränk aus gepresstem Obst" },
      { number: 4, dir: "down", row: 1, col: 7, answer: "SCHLANGE", clue: "Beinloses Reptil" },
      { number: 5, dir: "down", row: 2, col: 11, answer: "INTERNET", clue: "Weltweites Datennetz" },
      { number: 6, dir: "across", row: 3, col: 2, answer: "AUTO", clue: "Vierrädriges Fahrzeug" },
      { number: 7, dir: "down", row: 3, col: 9, answer: "SCHOKOLADE", clue: "Süße Nascherei aus Kakao" },
      { number: 8, dir: "across", row: 5, col: 2, answer: "WEIHNACHTEN", clue: "Fest im Dezember mit Geschenken" },
      { number: 8, dir: "down", row: 5, col: 2, answer: "WUERFEL", clue: "Sechsseitiger Zufallsgeber beim Spielen" },
      { number: 9, dir: "across", row: 9, col: 0, answer: "AFFE", clue: "Kletternder Verwandter des Menschen" },
      { number: 10, dir: "across", row: 10, col: 4, answer: "FLUGHAFEN", clue: "Wo Flugzeuge starten" },
      { number: 11, dir: "across", row: 11, col: 0, answer: "TAL", clue: "Senke zwischen zwei Bergen" },
      { number: 12, dir: "across", row: 12, col: 2, answer: "KARTOFFEL", clue: "Knolle, wird gekocht oder frittiert" },
    ],
  },
  {
    id: "cw-15",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, "W", null, "A", null, null, "F", null, "F", null, null, null],
      [null, null, "E", null, "P", null, null, "L", null, "U", null, "G", null],
      [null, "K", "I", "N", "O", null, "W", "U", "E", "S", "T", "E", null],
      ["S", null, "H", null, "T", null, null, "G", null, "S", null, "S", null],
      ["T", null, "N", null, "H", null, null, "H", null, "B", null, "C", null],
      ["R", null, "A", null, "E", null, null, "A", null, "A", null, "H", null],
      ["A", null, "C", null, "K", null, null, "F", null, "L", null, "E", null],
      ["S", "C", "H", "M", "E", "T", "T", "E", "R", "L", "I", "N", "G"],
      ["S", null, "T", null, null, "O", null, "N", null, null, null, "K", null],
      ["E", null, "E", null, null, "M", null, null, null, null, null, null, null],
      [null, null, "N", null, null, "A", "P", "F", "E", "L", null, null, null],
      [null, null, null, null, null, "T", null, null, null, null, null, null, null],
      [null, null, null, "K", "O", "E", "N", "I", "G", null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 2, answer: "WEIHNACHTEN", clue: "Fest im Dezember mit Geschenken" },
      { number: 2, dir: "down", row: 0, col: 4, answer: "APOTHEKE", clue: "Verkauft Medikamente" },
      { number: 3, dir: "down", row: 0, col: 7, answer: "FLUGHAFEN", clue: "Wo Flugzeuge starten" },
      { number: 4, dir: "down", row: 0, col: 9, answer: "FUSSBALL", clue: "Meistgespielte Ballsportart der Welt" },
      { number: 5, dir: "down", row: 1, col: 11, answer: "GESCHENK", clue: "Wird zum Geburtstag überreicht" },
      { number: 6, dir: "across", row: 2, col: 1, answer: "KINO", clue: "Ort zum Filmeschauen" },
      { number: 7, dir: "across", row: 2, col: 6, answer: "WUESTE", clue: "Sehr trockenes Gebiet voller Sand" },
      { number: 8, dir: "down", row: 3, col: 0, answer: "STRASSE", clue: "Für Autos und Fußgänger gebaut" },
      { number: 9, dir: "across", row: 7, col: 0, answer: "SCHMETTERLING", clue: "Bunt geflügeltes Insekt" },
      { number: 10, dir: "down", row: 7, col: 5, answer: "TOMATE", clue: "Rotes Gemüse, oft in Salaten" },
      { number: 11, dir: "across", row: 10, col: 5, answer: "APFEL", clue: "Rundes Obst, hält den Doktor fern" },
      { number: 12, dir: "across", row: 12, col: 3, answer: "KOENIG", clue: "Herrscher eines Königreichs" },
    ],
  },
  {
    id: "cw-16",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, "S", null, "A", "D", "L", "E", "R"],
      [null, null, "F", "R", "O", "S", "C", "H", null, "R", null, null, null],
      [null, null, "E", null, null, null, "H", null, "F", "A", "R", "B", "E"],
      [null, null, "E", null, null, null, "W", null, null, "C", null, null, null],
      [null, "K", "N", "O", "B", "L", "A", "U", "C", "H", null, null, null],
      [null, "A", null, null, null, null, "N", null, null, "E", null, null, "M"],
      ["K", "R", "O", "K", "O", "D", "I", "L", null, "K", null, null, "A"],
      [null, "T", null, null, null, null, null, null, null, "L", null, null, "L"],
      [null, "O", null, null, null, null, null, null, "K", "A", "E", "S", "E"],
      [null, "F", "A", "M", "I", "L", "I", "E", null, "V", null, null, "R"],
      [null, "F", null, null, null, null, null, null, null, "I", null, null, null],
      ["W", "E", "I", "H", "N", "A", "C", "H", "T", "E", "N", null, null],
      [null, "L", null, null, null, null, null, null, null, "R", null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 6, answer: "SCHWAN", clue: "Eleganter weißer Wasservogel" },
      { number: 2, dir: "across", row: 0, col: 8, answer: "ADLER", clue: "Greifvogel, Wappentier Deutschlands" },
      { number: 3, dir: "down", row: 0, col: 9, answer: "DRACHE", clue: "Feuerspeiendes Fabelwesen" },
      { number: 4, dir: "across", row: 1, col: 2, answer: "FROSCH", clue: "Springt und quakt am Teich" },
      { number: 4, dir: "down", row: 1, col: 2, answer: "FEE", clue: "Zauberhaftes Wesen mit Flügeln" },
      { number: 5, dir: "across", row: 2, col: 8, answer: "FARBE", clue: "Macht Bilder bunt" },
      { number: 6, dir: "across", row: 4, col: 1, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 6, dir: "down", row: 4, col: 1, answer: "KARTOFFEL", clue: "Knolle, wird gekocht oder frittiert" },
      { number: 7, dir: "down", row: 5, col: 12, answer: "MALER", clue: "Streicht Wände oder malt Bilder" },
      { number: 8, dir: "across", row: 6, col: 0, answer: "KROKODIL", clue: "Reptil mit vielen scharfen Zähnen im Wasser" },
      { number: 9, dir: "down", row: 6, col: 9, answer: "KLAVIER", clue: "Tasteninstrument mit vielen Tönen" },
      { number: 10, dir: "across", row: 8, col: 8, answer: "KAESE", clue: "Aus Milch hergestellt, viele Sorten" },
      { number: 11, dir: "across", row: 9, col: 1, answer: "FAMILIE", clue: "Eltern, Kinder und Verwandte" },
      { number: 12, dir: "across", row: 11, col: 0, answer: "WEIHNACHTEN", clue: "Fest im Dezember mit Geschenken" },
    ],
  },
  {
    id: "cw-17",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, null, "K", null, null, null, null],
      [null, null, null, null, null, null, "S", "T", "A", "D", "I", "O", "N"],
      [null, null, null, null, "F", null, null, null, "P", null, null, null, "A"],
      [null, null, "K", "O", "E", "N", "I", "G", "I", "N", null, null, "C"],
      [null, null, "N", null, "U", null, null, null, "T", null, "I", null, "H"],
      [null, null, "O", null, "E", null, "M", null, "A", null, "G", null, "T"],
      [null, null, "B", null, "R", null, "E", null, "E", null, "E", null, null],
      ["K", null, "L", null, "W", null, "D", null, "N", null, "L", null, null],
      ["A", null, "A", null, "E", null, "A", null, null, null, "E", null, "A"],
      ["F", "R", "U", "E", "H", "L", "I", "N", "G", null, "F", null, "U"],
      ["F", null, "C", null, "R", null, "L", null, null, "S", "A", "F", "T"],
      ["E", null, "H", null, null, null, "L", null, null, null, "N", null, "O"],
      ["E", null, null, "I", "N", "T", "E", "R", "N", "E", "T", null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 8, answer: "KAPITAEN", clue: "Führt ein Schiff" },
      { number: 2, dir: "across", row: 1, col: 6, answer: "STADION", clue: "Großer Sportaustragungsort" },
      { number: 3, dir: "down", row: 1, col: 12, answer: "NACHT", clue: "Dunkle Tageszeit" },
      { number: 4, dir: "down", row: 2, col: 4, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 5, dir: "across", row: 3, col: 2, answer: "KOENIGIN", clue: "Weibliche Herrscherin" },
      { number: 5, dir: "down", row: 3, col: 2, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 6, dir: "down", row: 4, col: 10, answer: "IGEL", clue: "Stacheliges Gartentier" },
      { number: 7, dir: "down", row: 5, col: 6, answer: "MEDAILLE", clue: "Auszeichnung für Sportler:innen" },
      { number: 8, dir: "down", row: 6, col: 10, answer: "ELEFANT", clue: "Größtes Landsäugetier" },
      { number: 9, dir: "down", row: 7, col: 0, answer: "KAFFEE", clue: "Koffeinhaltiges, warmes Getränk" },
      { number: 10, dir: "down", row: 8, col: 12, answer: "AUTO", clue: "Vierrädriges Fahrzeug" },
      { number: 11, dir: "across", row: 9, col: 0, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 12, dir: "across", row: 10, col: 9, answer: "SAFT", clue: "Getränk aus gepresstem Obst" },
      { number: 13, dir: "across", row: 12, col: 3, answer: "INTERNET", clue: "Weltweites Datennetz" },
    ],
  },
  {
    id: "cw-18",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, "G", "A", "R", "T", "E", "N"],
      [null, null, "S", "A", "L", "A", "T", null, null, null, "E", null, null],
      [null, null, null, null, null, "B", null, "S", null, null, "N", null, null],
      [null, null, null, null, "G", "E", "S", "C", "H", "E", "N", "K", null],
      [null, "F", null, null, null, "N", null, "H", null, null, "I", null, null],
      [null, "U", null, "K", null, "D", null, "W", null, null, "S", null, null],
      [null, "S", null, "A", null, null, "G", "I", "T", "A", "R", "R", "E"],
      [null, "S", null, "P", null, "K", null, "M", null, null, null, "I", null],
      [null, "B", null, "I", null, "A", null, "M", null, null, null, "T", null],
      ["K", "A", "R", "T", "O", "F", "F", "E", "L", null, null, "T", null],
      [null, "L", null, "A", null, "F", null, "N", null, null, null, "E", null],
      [null, "L", null, "E", null, "E", null, null, "S", "T", "U", "R", "M"],
      [null, null, "I", "N", "S", "E", "L", null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 7, answer: "GARTEN", clue: "Grünfläche zum Anpflanzen" },
      { number: 2, dir: "down", row: 0, col: 10, answer: "TENNIS", clue: "Sport mit Schläger und kleinem gelbem Ball" },
      { number: 3, dir: "across", row: 1, col: 2, answer: "SALAT", clue: "Grünes, frisches Gericht" },
      { number: 4, dir: "down", row: 1, col: 5, answer: "ABEND", clue: "Übergang zur Nacht" },
      { number: 5, dir: "down", row: 2, col: 7, answer: "SCHWIMMEN", clue: "Sportliche Fortbewegung im Wasser" },
      { number: 6, dir: "across", row: 3, col: 4, answer: "GESCHENK", clue: "Wird zum Geburtstag überreicht" },
      { number: 7, dir: "down", row: 4, col: 1, answer: "FUSSBALL", clue: "Meistgespielte Ballsportart der Welt" },
      { number: 8, dir: "down", row: 5, col: 3, answer: "KAPITAEN", clue: "Führt ein Schiff" },
      { number: 9, dir: "across", row: 6, col: 6, answer: "GITARRE", clue: "Saiteninstrument zum Zupfen" },
      { number: 10, dir: "down", row: 6, col: 11, answer: "RITTER", clue: "Gepanzerter Kämpfer im Mittelalter" },
      { number: 11, dir: "down", row: 7, col: 5, answer: "KAFFEE", clue: "Koffeinhaltiges, warmes Getränk" },
      { number: 12, dir: "across", row: 9, col: 0, answer: "KARTOFFEL", clue: "Knolle, wird gekocht oder frittiert" },
      { number: 13, dir: "across", row: 11, col: 8, answer: "STURM", clue: "Sehr starker Wind" },
      { number: 14, dir: "across", row: 12, col: 2, answer: "INSEL", clue: "Von Wasser umgebenes Land" },
    ],
  },
  {
    id: "cw-19",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, "M", null, null, null, null, null, null, null, null, null, null],
      ["Z", null, "E", null, "G", "I", "R", "A", "F", "F", "E", null, null],
      ["U", null, "D", null, null, null, null, null, "E", null, null, null, null],
      ["G", null, "A", null, "G", null, "S", null, "U", null, null, null, null],
      ["E", null, "I", null, "E", null, "C", null, "E", null, null, null, null],
      ["B", "I", "L", "D", "S", "C", "H", "I", "R", "M", null, "M", null],
      ["U", null, "L", null, "C", null, "W", null, "W", null, null, "A", null],
      ["R", null, "E", null, "H", null, "I", null, "E", null, "S", "E", "E"],
      ["T", null, null, null, "E", null, "M", null, "H", null, null, "R", null],
      ["S", null, null, null, "N", null, "M", null, "R", null, null, "C", null],
      ["T", "O", "R", null, "K", null, "E", null, null, null, null, "H", null],
      ["A", null, null, null, null, "I", "N", "T", "E", "R", "N", "E", "T"],
      ["G", null, null, null, null, null, null, null, "I", null, null, "N", null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 2, answer: "MEDAILLE", clue: "Auszeichnung für Sportler:innen" },
      { number: 2, dir: "down", row: 1, col: 0, answer: "ZUG", clue: "Fährt auf Schienen" },
      { number: 3, dir: "across", row: 1, col: 4, answer: "GIRAFFE", clue: "Tier mit dem längsten Hals" },
      { number: 4, dir: "down", row: 1, col: 8, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 5, dir: "down", row: 3, col: 0, answer: "GEBURTSTAG", clue: "Jährlicher Feiertag der eigenen Geburt" },
      { number: 6, dir: "down", row: 3, col: 4, answer: "GESCHENK", clue: "Wird zum Geburtstag überreicht" },
      { number: 7, dir: "down", row: 3, col: 6, answer: "SCHWIMMEN", clue: "Sportliche Fortbewegung im Wasser" },
      { number: 8, dir: "across", row: 5, col: 0, answer: "BILDSCHIRM", clue: "Zeigt Inhalte am Computer an" },
      { number: 9, dir: "down", row: 5, col: 11, answer: "MAERCHEN", clue: "Fantastische Erzählung für Kinder" },
      { number: 10, dir: "across", row: 7, col: 10, answer: "SEE", clue: "Stehendes Binnengewässer" },
      { number: 11, dir: "across", row: 10, col: 0, answer: "TOR", clue: "Ziel beim Fußball" },
      { number: 12, dir: "across", row: 11, col: 5, answer: "INTERNET", clue: "Weltweites Datennetz" },
      { number: 13, dir: "down", row: 11, col: 8, answer: "EI", clue: "Legt das Huhn" },
    ],
  },
  {
    id: "cw-20",
    rows: 12,
    cols: 13,
    grid: [
      ["V", null, "G", "R", "A", "S", null, "K", "U", "C", "H", "E", "N"],
      ["U", null, "I", null, null, null, "P", null, "R", null, "A", null, "A"],
      ["L", null, "T", null, null, null, "I", null, "L", null, "U", null, "C"],
      ["K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S", null, "H"],
      ["A", null, "R", null, "A", null, "G", null, "U", null, "C", null, "T"],
      ["N", null, "R", null, "P", null, "U", null, "B", null, "H", null, null],
      ["K", "O", "E", "N", "I", "G", "I", "N", null, null, "W", null, null],
      [null, null, null, null, "T", null, "N", null, null, null, "I", null, null],
      [null, null, null, null, "A", null, null, null, null, null, "M", null, null],
      [null, "I", "N", "T", "E", "R", "N", "E", "T", null, "M", null, null],
      [null, null, null, null, "N", null, null, null, null, null, "E", null, null],
      [null, null, null, null, "G", "E", "S", "C", "H", "E", "N", "K", null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 0, answer: "VULKAN", clue: "Berg, der Lava spuckt" },
      { number: 2, dir: "across", row: 0, col: 2, answer: "GRAS", clue: "Grüner Bodenbewuchs" },
      { number: 2, dir: "down", row: 0, col: 2, answer: "GITARRE", clue: "Saiteninstrument zum Zupfen" },
      { number: 3, dir: "across", row: 0, col: 7, answer: "KUCHEN", clue: "Süßes Gebäck zum Kaffee" },
      { number: 4, dir: "down", row: 0, col: 8, answer: "URLAUB", clue: "Freie Zeit zum Erholen" },
      { number: 5, dir: "down", row: 0, col: 10, answer: "HAUS", clue: "Wo man wohnt" },
      { number: 6, dir: "down", row: 0, col: 12, answer: "NACHT", clue: "Dunkle Tageszeit" },
      { number: 7, dir: "down", row: 1, col: 6, answer: "PINGUIN", clue: "Flugunfähiger Vogel der Antarktis" },
      { number: 8, dir: "across", row: 3, col: 0, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 9, dir: "down", row: 3, col: 4, answer: "KAPITAEN", clue: "Führt ein Schiff" },
      { number: 10, dir: "down", row: 3, col: 10, answer: "SCHWIMMEN", clue: "Sportliche Fortbewegung im Wasser" },
      { number: 11, dir: "across", row: 6, col: 0, answer: "KOENIGIN", clue: "Weibliche Herrscherin" },
      { number: 12, dir: "across", row: 9, col: 1, answer: "INTERNET", clue: "Weltweites Datennetz" },
      { number: 13, dir: "across", row: 11, col: 4, answer: "GESCHENK", clue: "Wird zum Geburtstag überreicht" },
    ],
  },
  {
    id: "cw-21",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, null, null, null, "T", null, "K"],
      [null, "H", null, null, null, "D", "O", "N", "N", "E", "R", null, "O"],
      ["B", "O", "O", "T", null, null, null, null, null, null, "O", null, "E"],
      [null, "E", null, null, "S", "C", "H", "W", "I", "M", "M", "E", "N"],
      [null, "H", null, null, "C", null, null, null, null, null, "M", null, "I"],
      ["F", "L", "U", "G", "H", "A", "F", "E", "N", null, "E", null, "G"],
      [null, "E", null, null, "O", null, null, null, null, null, "L", null, "I"],
      ["K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S", null, "N"],
      ["I", null, null, null, "O", null, null, null, null, null, null, null, null],
      ["N", null, null, null, "L", null, null, null, null, null, null, null, null],
      ["O", null, null, "Z", "A", "U", "B", "E", "R", "E", "R", null, null],
      [null, null, null, null, "D", null, null, null, null, null, null, null, null],
      [null, "F", "R", "U", "E", "H", "L", "I", "N", "G", null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 10, answer: "TROMMEL", clue: "Schlaginstrument" },
      { number: 2, dir: "down", row: 0, col: 12, answer: "KOENIGIN", clue: "Weibliche Herrscherin" },
      { number: 3, dir: "down", row: 1, col: 1, answer: "HOEHLE", clue: "Dunkler Raum im Fels" },
      { number: 4, dir: "across", row: 1, col: 5, answer: "DONNER", clue: "Grollt nach dem Blitz" },
      { number: 5, dir: "across", row: 2, col: 0, answer: "BOOT", clue: "Kleines Wasserfahrzeug" },
      { number: 6, dir: "across", row: 3, col: 4, answer: "SCHWIMMEN", clue: "Sportliche Fortbewegung im Wasser" },
      { number: 6, dir: "down", row: 3, col: 4, answer: "SCHOKOLADE", clue: "Süße Nascherei aus Kakao" },
      { number: 7, dir: "across", row: 5, col: 0, answer: "FLUGHAFEN", clue: "Wo Flugzeuge starten" },
      { number: 8, dir: "across", row: 7, col: 0, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 8, dir: "down", row: 7, col: 0, answer: "KINO", clue: "Ort zum Filmeschauen" },
      { number: 9, dir: "across", row: 10, col: 3, answer: "ZAUBERER", clue: "Wirkt in Märchen mit Magie" },
      { number: 10, dir: "across", row: 12, col: 1, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
    ],
  },
  {
    id: "cw-22",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, "D", null, null, null, null, "B", "E", "R", "G", null, null],
      ["H", "O", "E", "H", "L", "E", null, "A", null, null, null, null, null],
      [null, null, "L", null, null, null, null, "E", null, null, null, null, null],
      [null, "P", "F", "E", "F", "F", "E", "R", null, null, null, null, null],
      [null, null, "I", null, null, "R", null, null, "M", null, null, null, null],
      [null, null, "N", null, null, "U", null, null, "A", null, "K", null, null],
      ["T", "H", "E", "A", "T", "E", "R", null, "E", null, "A", null, "F"],
      ["R", null, null, null, null, "H", null, null, "R", null, "P", null, "A"],
      ["A", null, null, "B", "I", "L", "D", "S", "C", "H", "I", "R", "M"],
      ["I", null, null, null, null, "I", null, null, "H", null, "T", null, "I"],
      ["N", null, null, "B", "A", "N", "A", "N", "E", null, "A", null, "L"],
      ["E", null, null, "U", null, "G", null, null, "N", null, "E", null, "I"],
      ["R", null, null, "S", null, null, null, null, null, null, "N", null, "E"],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 2, answer: "DELFIN", clue: "Intelligentes Meeressäugetier" },
      { number: 2, dir: "across", row: 0, col: 7, answer: "BERG", clue: "Hohe Erhebung der Landschaft" },
      { number: 2, dir: "down", row: 0, col: 7, answer: "BAER", clue: "Brummt und liebt Honig" },
      { number: 3, dir: "across", row: 1, col: 0, answer: "HOEHLE", clue: "Dunkler Raum im Fels" },
      { number: 4, dir: "across", row: 3, col: 1, answer: "PFEFFER", clue: "Scharfes Gewürz aus kleinen Körnern" },
      { number: 5, dir: "down", row: 3, col: 5, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 6, dir: "down", row: 4, col: 8, answer: "MAERCHEN", clue: "Fantastische Erzählung für Kinder" },
      { number: 7, dir: "down", row: 5, col: 10, answer: "KAPITAEN", clue: "Führt ein Schiff" },
      { number: 8, dir: "across", row: 6, col: 0, answer: "THEATER", clue: "Ort für Bühnenstücke" },
      { number: 8, dir: "down", row: 6, col: 0, answer: "TRAINER", clue: "Leitet das Team beim Training" },
      { number: 9, dir: "down", row: 6, col: 12, answer: "FAMILIE", clue: "Eltern, Kinder und Verwandte" },
      { number: 10, dir: "across", row: 8, col: 3, answer: "BILDSCHIRM", clue: "Zeigt Inhalte am Computer an" },
      { number: 11, dir: "across", row: 10, col: 3, answer: "BANANE", clue: "Gelbes, krummes Obst" },
      { number: 11, dir: "down", row: 10, col: 3, answer: "BUS", clue: "Öffentliches Fahrzeug für viele Personen" },
    ],
  },
  {
    id: "cw-23",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, "F", null, "O", "S", "T", "E", "R", "N", null],
      ["Z", "E", "B", "R", "A", null, null, "C", null, null, null, null, null],
      [null, null, null, null, "R", null, null, "H", "E", "R", "B", "S", "T"],
      ["F", "U", "S", "S", "B", "A", "L", "L", null, null, null, "C", null],
      ["E", null, "C", null, "E", null, null, "O", null, "T", null, "H", null],
      ["N", null, "H", null, null, "A", null, "S", null, "A", null, "W", null],
      ["S", null, "O", null, null, "P", null, "S", null, "S", null, "A", null],
      ["T", null, "K", null, null, "O", null, null, null, "T", null, "N", null],
      ["E", null, "O", null, null, "T", null, "J", null, "A", null, null, null],
      ["R", null, "L", null, null, "H", null, "A", null, "T", null, null, null],
      ["K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S", null, null],
      [null, null, "D", null, null, "K", null, "R", null, "R", null, null, null],
      ["W", "U", "E", "R", "F", "E", "L", null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 4, answer: "FARBE", clue: "Macht Bilder bunt" },
      { number: 2, dir: "across", row: 0, col: 6, answer: "OSTERN", clue: "Fest mit Eiern und Hasen im Frühling" },
      { number: 3, dir: "down", row: 0, col: 7, answer: "SCHLOSS", clue: "Prunkvolles Adelsgebäude" },
      { number: 4, dir: "across", row: 1, col: 0, answer: "ZEBRA", clue: "Gestreiftes Steppentier" },
      { number: 5, dir: "across", row: 2, col: 7, answer: "HERBST", clue: "Jahreszeit mit buntem Laub" },
      { number: 6, dir: "down", row: 2, col: 11, answer: "SCHWAN", clue: "Eleganter weißer Wasservogel" },
      { number: 7, dir: "across", row: 3, col: 0, answer: "FUSSBALL", clue: "Meistgespielte Ballsportart der Welt" },
      { number: 7, dir: "down", row: 3, col: 0, answer: "FENSTER", clue: "Durchsichtige Öffnung in der Wand" },
      { number: 8, dir: "down", row: 3, col: 2, answer: "SCHOKOLADE", clue: "Süße Nascherei aus Kakao" },
      { number: 9, dir: "down", row: 4, col: 9, answer: "TASTATUR", clue: "Zum Tippen am Computer" },
      { number: 10, dir: "down", row: 5, col: 5, answer: "APOTHEKE", clue: "Verkauft Medikamente" },
      { number: 11, dir: "down", row: 8, col: 7, answer: "JAHR", clue: "Zwölf Monate" },
      { number: 12, dir: "across", row: 10, col: 0, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 13, dir: "across", row: 12, col: 0, answer: "WUERFEL", clue: "Sechsseitiger Zufallsgeber beim Spielen" },
    ],
  },
  {
    id: "cw-24",
    rows: 12,
    cols: 13,
    grid: [
      ["P", null, null, null, null, null, "T", null, null, null, null, null, null],
      ["A", null, null, null, null, null, "E", null, "B", null, "G", null, "S"],
      ["S", null, null, "A", "F", "F", "E", null, "I", null, "E", null, "C"],
      ["S", null, "S", null, null, "R", null, null, "L", null, "B", null, "H"],
      ["C", null, "C", null, "Z", "U", "G", null, "D", null, "U", null, "L"],
      ["H", null, "H", null, null, "E", null, null, "S", null, "R", null, "A"],
      ["L", null, "W", "E", "I", "H", "N", "A", "C", "H", "T", "E", "N"],
      ["A", null, "I", null, null, "L", null, null, "H", null, "S", null, "G"],
      ["F", "A", "M", "I", "L", "I", "E", null, "I", null, "T", null, "E"],
      [null, null, "M", null, null, "N", null, null, "R", null, "A", null, null],
      [null, null, "E", null, null, "G", null, null, "M", null, "G", null, null],
      ["M", "O", "N", "A", "T", null, null, null, null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 0, answer: "PASS", clue: "Wichtiges Reisedokument" },
      { number: 2, dir: "down", row: 0, col: 6, answer: "TEE", clue: "Aufgussgetränk aus Blättern" },
      { number: 3, dir: "down", row: 1, col: 8, answer: "BILDSCHIRM", clue: "Zeigt Inhalte am Computer an" },
      { number: 4, dir: "down", row: 1, col: 10, answer: "GEBURTSTAG", clue: "Jährlicher Feiertag der eigenen Geburt" },
      { number: 5, dir: "down", row: 1, col: 12, answer: "SCHLANGE", clue: "Beinloses Reptil" },
      { number: 6, dir: "across", row: 2, col: 3, answer: "AFFE", clue: "Kletternder Verwandter des Menschen" },
      { number: 7, dir: "down", row: 2, col: 5, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 8, dir: "down", row: 3, col: 0, answer: "SCHLAF", clue: "Nächtliche Erholung" },
      { number: 9, dir: "down", row: 3, col: 2, answer: "SCHWIMMEN", clue: "Sportliche Fortbewegung im Wasser" },
      { number: 10, dir: "across", row: 4, col: 4, answer: "ZUG", clue: "Fährt auf Schienen" },
      { number: 11, dir: "across", row: 6, col: 2, answer: "WEIHNACHTEN", clue: "Fest im Dezember mit Geschenken" },
      { number: 12, dir: "across", row: 8, col: 0, answer: "FAMILIE", clue: "Eltern, Kinder und Verwandte" },
      { number: 13, dir: "across", row: 11, col: 0, answer: "MONAT", clue: "Etwa vier Wochen" },
    ],
  },
  {
    id: "cw-25",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, "D", "O", "N", "N", "E", "R", null, null, null, null],
      [null, null, "H", null, null, null, null, null, "O", null, null, null, null],
      [null, null, "A", null, null, null, null, null, "B", null, null, "W", null],
      ["F", null, "U", null, "K", "A", "R", "T", "O", "F", "F", "E", "L"],
      ["U", null, "S", null, null, null, null, null, "T", null, null, "I", null],
      ["S", null, "C", null, null, null, null, null, "E", null, null, "H", null],
      ["S", "C", "H", "M", "E", "T", "T", "E", "R", "L", "I", "N", "G"],
      ["B", null, "L", null, "I", null, null, null, null, null, null, "A", null],
      ["A", null, "O", null, "S", null, null, null, null, null, null, "C", null],
      ["L", null, "S", "T", "U", "D", "E", "N", "T", null, null, "H", null],
      ["L", null, "S", null, null, null, null, null, "A", null, null, "T", null],
      [null, null, "S", "C", "H", "O", "K", "O", "L", "A", "D", "E", null],
      [null, null, null, null, null, null, null, null, null, null, null, "N", null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 3, answer: "DONNER", clue: "Grollt nach dem Blitz" },
      { number: 2, dir: "down", row: 0, col: 8, answer: "ROBOTER", clue: "Maschine, die menschliche Arbeit übernimmt" },
      { number: 3, dir: "down", row: 1, col: 2, answer: "HAUS", clue: "Wo man wohnt" },
      { number: 4, dir: "down", row: 2, col: 11, answer: "WEIHNACHTEN", clue: "Fest im Dezember mit Geschenken" },
      { number: 5, dir: "down", row: 3, col: 0, answer: "FUSSBALL", clue: "Meistgespielte Ballsportart der Welt" },
      { number: 6, dir: "across", row: 3, col: 4, answer: "KARTOFFEL", clue: "Knolle, wird gekocht oder frittiert" },
      { number: 7, dir: "down", row: 4, col: 2, answer: "SCHLOSS", clue: "Prunkvolles Adelsgebäude" },
      { number: 8, dir: "across", row: 6, col: 0, answer: "SCHMETTERLING", clue: "Bunt geflügeltes Insekt" },
      { number: 9, dir: "down", row: 6, col: 4, answer: "EIS", clue: "Gefrorenes Wasser" },
      { number: 10, dir: "across", row: 9, col: 2, answer: "STUDENT", clue: "Lernt an der Universität" },
      { number: 11, dir: "down", row: 9, col: 8, answer: "TAL", clue: "Senke zwischen zwei Bergen" },
      { number: 12, dir: "across", row: 11, col: 2, answer: "SCHOKOLADE", clue: "Süße Nascherei aus Kakao" },
    ],
  },
  {
    id: "cw-26",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, "T", "R", "A", "U", "M", null],
      [null, "K", "O", "F", "F", "E", "R", null, null, null, null, "U", null],
      [null, "I", null, null, null, null, null, null, null, null, null, "S", null],
      [null, "R", "I", "T", "T", "E", "R", null, "M", "A", "L", "E", "R"],
      [null, "C", null, null, null, null, null, "I", null, null, null, "U", null],
      [null, "H", null, "F", null, null, null, "N", null, "F", null, "M", null],
      ["K", "E", "L", "L", "E", "R", null, "T", null, "U", null, "E", null],
      [null, null, null, "U", null, null, null, "E", null, "S", null, "D", null],
      [null, null, null, "G", "E", "B", "U", "R", "T", "S", "T", "A", "G"],
      ["S", "A", "L", "Z", null, null, null, "N", null, "B", null, "I", null],
      [null, null, null, "E", null, null, null, "E", null, "A", null, "L", null],
      [null, "S", "T", "U", "D", "E", "N", "T", null, "L", null, "L", null],
      [null, null, null, "G", null, null, null, null, null, "L", null, "E", null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 7, answer: "TRAUM", clue: "Erlebnis während des Schlafs" },
      { number: 2, dir: "down", row: 0, col: 11, answer: "MUSEUM", clue: "Ort für Kunst und Ausstellungen" },
      { number: 3, dir: "across", row: 1, col: 1, answer: "KOFFER", clue: "Für die Reise gepackt" },
      { number: 3, dir: "down", row: 1, col: 1, answer: "KIRCHE", clue: "Gebäude für Gottesdienste" },
      { number: 4, dir: "across", row: 3, col: 1, answer: "RITTER", clue: "Gepanzerter Kämpfer im Mittelalter" },
      { number: 5, dir: "across", row: 3, col: 8, answer: "MALER", clue: "Streicht Wände oder malt Bilder" },
      { number: 6, dir: "down", row: 4, col: 7, answer: "INTERNET", clue: "Weltweites Datennetz" },
      { number: 7, dir: "down", row: 5, col: 3, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
      { number: 8, dir: "down", row: 5, col: 9, answer: "FUSSBALL", clue: "Meistgespielte Ballsportart der Welt" },
      { number: 9, dir: "down", row: 5, col: 11, answer: "MEDAILLE", clue: "Auszeichnung für Sportler:innen" },
      { number: 10, dir: "across", row: 6, col: 0, answer: "KELLER", clue: "Unterster Raum eines Hauses" },
      { number: 11, dir: "across", row: 8, col: 3, answer: "GEBURTSTAG", clue: "Jährlicher Feiertag der eigenen Geburt" },
      { number: 12, dir: "across", row: 9, col: 0, answer: "SALZ", clue: "Würzt fast jedes Gericht" },
      { number: 13, dir: "across", row: 11, col: 1, answer: "STUDENT", clue: "Lernt an der Universität" },
    ],
  },
  {
    id: "cw-27",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, null, null, "G", "U", "R", "K", "E"],
      [null, "F", null, null, null, null, null, null, null, null, null, "U", null],
      [null, "E", null, null, null, null, null, null, null, "K", "O", "C", "H"],
      ["Z", "U", "C", "K", "E", "R", null, null, "Z", null, null, "H", null],
      [null, "E", null, "N", null, null, "K", "L", "A", "V", "I", "E", "R"],
      [null, "R", null, "O", null, "A", null, null, "U", null, null, "N", null],
      [null, "K", null, "B", null, "P", null, null, "B", null, null, null, null],
      [null, "O", null, "L", null, "O", null, "H", "E", "R", "B", "S", "T"],
      [null, "F", null, "A", null, "T", null, null, "R", null, null, "U", null],
      [null, "F", "L", "U", "G", "H", "A", "F", "E", "N", null, "P", null],
      [null, "E", null, "C", null, "E", null, null, "R", null, null, "P", null],
      [null, "R", null, "H", null, "K", null, null, null, null, null, "E", null],
      [null, null, null, null, "F", "E", "N", "S", "T", "E", "R", null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 8, answer: "GURKE", clue: "Grünes, längliches Gemüse" },
      { number: 2, dir: "down", row: 0, col: 11, answer: "KUCHEN", clue: "Süßes Gebäck zum Kaffee" },
      { number: 3, dir: "down", row: 1, col: 1, answer: "FEUER", clue: "Heiß, hell, verbrennt Holz" },
      { number: 4, dir: "across", row: 2, col: 9, answer: "KOCH", clue: "Bereitet Speisen im Restaurant zu" },
      { number: 5, dir: "across", row: 3, col: 0, answer: "ZUCKER", clue: "Macht Speisen süß" },
      { number: 6, dir: "down", row: 3, col: 3, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 7, dir: "down", row: 3, col: 8, answer: "ZAUBERER", clue: "Wirkt in Märchen mit Magie" },
      { number: 8, dir: "across", row: 4, col: 6, answer: "KLAVIER", clue: "Tasteninstrument mit vielen Tönen" },
      { number: 9, dir: "down", row: 5, col: 5, answer: "APOTHEKE", clue: "Verkauft Medikamente" },
      { number: 10, dir: "down", row: 6, col: 1, answer: "KOFFER", clue: "Für die Reise gepackt" },
      { number: 11, dir: "across", row: 7, col: 7, answer: "HERBST", clue: "Jahreszeit mit buntem Laub" },
      { number: 12, dir: "down", row: 7, col: 11, answer: "SUPPE", clue: "Flüssiges, warmes Gericht" },
      { number: 13, dir: "across", row: 9, col: 1, answer: "FLUGHAFEN", clue: "Wo Flugzeuge starten" },
      { number: 14, dir: "across", row: 12, col: 4, answer: "FENSTER", clue: "Durchsichtige Öffnung in der Wand" },
    ],
  },
  {
    id: "cw-28",
    rows: 13,
    cols: 13,
    grid: [
      [null, "P", "I", "Z", "Z", "A", null, null, null, null, null, null, "T"],
      [null, "O", null, null, null, null, null, null, "K", "A", "T", "Z", "E"],
      [null, "K", null, null, "T", null, null, null, "A", null, "A", null, "N"],
      ["B", "A", "H", "N", "H", "O", "F", null, "L", null, "S", null, "N"],
      [null, "L", null, null, "E", null, null, null, "E", null, "T", null, "I"],
      [null, null, "K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S"],
      [null, null, "L", null, "T", null, "R", null, "D", null, "T", null, null],
      [null, null, "A", null, "E", null, "O", null, "E", null, "U", null, null],
      [null, null, "V", null, "R", null, "K", null, "R", null, "R", null, null],
      ["W", "E", "I", "N", null, null, "O", null, null, null, null, null, null],
      [null, null, "E", null, "M", "E", "D", "A", "I", "L", "L", "E", null],
      [null, null, "R", null, null, null, "I", null, null, null, null, null, null],
      [null, null, null, "S", "C", "H", "L", "A", "N", "G", "E", null, null],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 1, answer: "PIZZA", clue: "Italienisches Fladengericht mit Belag" },
      { number: 1, dir: "down", row: 0, col: 1, answer: "POKAL", clue: "Trophäe für den Sieger" },
      { number: 2, dir: "down", row: 0, col: 12, answer: "TENNIS", clue: "Sport mit Schläger und kleinem gelbem Ball" },
      { number: 3, dir: "across", row: 1, col: 8, answer: "KATZE", clue: "Schnurrendes Haustier" },
      { number: 3, dir: "down", row: 1, col: 8, answer: "KALENDER", clue: "Zeigt Tage und Monate an" },
      { number: 4, dir: "down", row: 1, col: 10, answer: "TASTATUR", clue: "Zum Tippen am Computer" },
      { number: 5, dir: "down", row: 2, col: 4, answer: "THEATER", clue: "Ort für Bühnenstücke" },
      { number: 6, dir: "across", row: 3, col: 0, answer: "BAHNHOF", clue: "Wo Züge abfahren" },
      { number: 7, dir: "across", row: 5, col: 2, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 7, dir: "down", row: 5, col: 2, answer: "KLAVIER", clue: "Tasteninstrument mit vielen Tönen" },
      { number: 8, dir: "down", row: 5, col: 6, answer: "KROKODIL", clue: "Reptil mit vielen scharfen Zähnen im Wasser" },
      { number: 9, dir: "across", row: 9, col: 0, answer: "WEIN", clue: "Alkoholisches Getränk aus Trauben" },
      { number: 10, dir: "across", row: 10, col: 4, answer: "MEDAILLE", clue: "Auszeichnung für Sportler:innen" },
      { number: 11, dir: "across", row: 12, col: 3, answer: "SCHLANGE", clue: "Beinloses Reptil" },
    ],
  },
  {
    id: "cw-29",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, "H", null, "B", "A", "U", "E", "R", null, null, null, "B"],
      [null, null, "E", null, "U", null, null, null, null, null, "K", null, "U"],
      [null, null, "R", null, "T", "R", "O", "M", "M", "E", "L", null, "S"],
      [null, null, "B", null, "T", null, null, null, null, null, "A", null, "T"],
      [null, "O", "S", "T", "E", "R", "N", null, null, null, "V", null, "U"],
      [null, null, "T", null, "R", null, null, "C", null, null, "I", null, "D"],
      ["G", null, "A", null, null, "A", "P", "O", "T", "H", "E", "K", "E"],
      ["I", null, "S", null, null, null, null, "M", null, null, "R", null, "N"],
      ["R", null, "T", null, null, null, null, "P", null, null, null, null, "T"],
      ["A", null, "A", null, null, "Z", "A", "U", "B", "E", "R", "E", "R"],
      ["F", null, "T", null, null, null, null, "T", null, null, null, null, null],
      ["F", "L", "U", "G", "H", "A", "F", "E", "N", null, null, null, null],
      ["E", null, "R", null, null, null, null, "R", null, null, null, null, null],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 2, answer: "HERBST", clue: "Jahreszeit mit buntem Laub" },
      { number: 2, dir: "across", row: 0, col: 4, answer: "BAUER", clue: "Bewirtschaftet Felder und Höfe" },
      { number: 2, dir: "down", row: 0, col: 4, answer: "BUTTER", clue: "Streichfett aus Milch" },
      { number: 3, dir: "down", row: 0, col: 12, answer: "BUS", clue: "Öffentliches Fahrzeug für viele Personen" },
      { number: 4, dir: "down", row: 1, col: 10, answer: "KLAVIER", clue: "Tasteninstrument mit vielen Tönen" },
      { number: 5, dir: "across", row: 2, col: 4, answer: "TROMMEL", clue: "Schlaginstrument" },
      { number: 6, dir: "down", row: 2, col: 12, answer: "STUDENT", clue: "Lernt an der Universität" },
      { number: 7, dir: "across", row: 4, col: 1, answer: "OSTERN", clue: "Fest mit Eiern und Hasen im Frühling" },
      { number: 8, dir: "down", row: 5, col: 2, answer: "TASTATUR", clue: "Zum Tippen am Computer" },
      { number: 9, dir: "down", row: 5, col: 7, answer: "COMPUTER", clue: "Elektronisches Rechengerät" },
      { number: 10, dir: "down", row: 6, col: 0, answer: "GIRAFFE", clue: "Tier mit dem längsten Hals" },
      { number: 11, dir: "across", row: 6, col: 5, answer: "APOTHEKE", clue: "Verkauft Medikamente" },
      { number: 12, dir: "across", row: 9, col: 5, answer: "ZAUBERER", clue: "Wirkt in Märchen mit Magie" },
      { number: 13, dir: "across", row: 11, col: 0, answer: "FLUGHAFEN", clue: "Wo Flugzeuge starten" },
    ],
  },
  {
    id: "cw-30",
    rows: 13,
    cols: 13,
    grid: [
      [null, null, null, null, null, null, "K", "E", "R", "Z", "E", null, null],
      [null, null, "B", null, null, null, "O", null, null, null, null, null, null],
      ["K", null, "R", null, null, null, "E", "L", "E", "F", "A", "N", "T"],
      ["R", null, "U", null, "S", null, "N", null, null, null, "P", null, "H"],
      ["A", null, "E", null, "C", null, "I", null, "F", null, "O", null, "E"],
      ["N", null, "C", null, "H", null, "G", null, "E", null, "T", null, "A"],
      ["K", null, "K", "N", "O", "B", "L", "A", "U", "C", "H", null, "T"],
      ["E", null, "E", null, "K", null, "E", null, "E", null, "E", null, "E"],
      ["N", null, null, null, "O", null, "H", null, "R", null, "K", null, "R"],
      ["H", null, "M", "A", "L", "E", "R", null, "W", null, "E", null, null],
      ["A", null, null, null, "A", null, "E", null, "E", null, null, null, null],
      ["U", null, null, null, "D", null, "R", null, "H", null, null, null, null],
      ["S", "C", "H", "M", "E", "T", "T", "E", "R", "L", "I", "N", "G"],
    ],
    entries: [
      { number: 1, dir: "across", row: 0, col: 6, answer: "KERZE", clue: "Brennt mit einem Docht" },
      { number: 1, dir: "down", row: 0, col: 6, answer: "KOENIG", clue: "Herrscher eines Königreichs" },
      { number: 2, dir: "down", row: 1, col: 2, answer: "BRUECKE", clue: "Führt über einen Fluss" },
      { number: 3, dir: "down", row: 2, col: 0, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 4, dir: "across", row: 2, col: 6, answer: "ELEFANT", clue: "Größtes Landsäugetier" },
      { number: 5, dir: "down", row: 2, col: 10, answer: "APOTHEKE", clue: "Verkauft Medikamente" },
      { number: 6, dir: "down", row: 2, col: 12, answer: "THEATER", clue: "Ort für Bühnenstücke" },
      { number: 7, dir: "down", row: 3, col: 4, answer: "SCHOKOLADE", clue: "Süße Nascherei aus Kakao" },
      { number: 8, dir: "down", row: 4, col: 8, answer: "FEUERWEHR", clue: "Löscht Brände" },
      { number: 9, dir: "across", row: 6, col: 2, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 10, dir: "down", row: 6, col: 6, answer: "LEHRER", clue: "Unterrichtet in der Schule" },
      { number: 11, dir: "across", row: 9, col: 2, answer: "MALER", clue: "Streicht Wände oder malt Bilder" },
      { number: 12, dir: "across", row: 12, col: 0, answer: "SCHMETTERLING", clue: "Bunt geflügeltes Insekt" },
    ],
  },
  {
    id: "cw-31",
    rows: 13,
    cols: 13,
    grid: [
      ["L", null, null, null, "S", "T", "U", "H", "L", null, "R", null, null],
      ["U", null, null, null, null, null, null, null, "O", null, "E", null, null],
      ["F", null, null, "F", "L", "U", "G", "Z", "E", "U", "G", null, null],
      ["T", "U", "E", "R", null, null, null, null, "W", null, "E", null, null],
      [null, null, null, "U", null, null, null, null, "E", null, "N", null, null],
      [null, null, "T", "E", "L", "E", "F", "O", "N", null, "C", null, "K"],
      [null, "T", null, "H", null, null, null, null, null, null, "O", null, "O"],
      [null, "R", null, "L", null, null, null, null, null, null, "M", null, "E"],
      ["F", "A", "M", "I", "L", "I", "E", null, null, null, "P", null, "N"],
      [null, "I", null, "N", null, null, null, null, null, null, "U", null, "I"],
      [null, "N", null, "G", "E", "B", "U", "R", "T", "S", "T", "A", "G"],
      [null, "E", null, null, null, null, null, null, null, null, "E", null, "I"],
      [null, "R", null, "K", "A", "L", "E", "N", "D", "E", "R", null, "N"],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 0, answer: "LUFT", clue: "Zum Atmen nötiges Gas-Gemisch" },
      { number: 2, dir: "across", row: 0, col: 4, answer: "STUHL", clue: "Möbelstück zum Sitzen" },
      { number: 3, dir: "down", row: 0, col: 8, answer: "LOEWE", clue: "König der Tiere" },
      { number: 4, dir: "down", row: 0, col: 10, answer: "REGEN", clue: "Fällt aus Wolken" },
      { number: 5, dir: "across", row: 2, col: 3, answer: "FLUGZEUG", clue: "Fliegt hoch am Himmel" },
      { number: 5, dir: "down", row: 2, col: 3, answer: "FRUEHLING", clue: "Jahreszeit des Erwachens" },
      { number: 6, dir: "across", row: 3, col: 0, answer: "TUER", clue: "Zum Öffnen und Schließen eines Raums" },
      { number: 7, dir: "across", row: 5, col: 2, answer: "TELEFON", clue: "Gerät zum Anrufen" },
      { number: 8, dir: "down", row: 5, col: 10, answer: "COMPUTER", clue: "Elektronisches Rechengerät" },
      { number: 9, dir: "down", row: 5, col: 12, answer: "KOENIGIN", clue: "Weibliche Herrscherin" },
      { number: 10, dir: "down", row: 6, col: 1, answer: "TRAINER", clue: "Leitet das Team beim Training" },
      { number: 11, dir: "across", row: 8, col: 0, answer: "FAMILIE", clue: "Eltern, Kinder und Verwandte" },
      { number: 12, dir: "across", row: 10, col: 3, answer: "GEBURTSTAG", clue: "Jährlicher Feiertag der eigenen Geburt" },
      { number: 13, dir: "across", row: 12, col: 3, answer: "KALENDER", clue: "Zeigt Tage und Monate an" },
    ],
  },
  {
    id: "cw-32",
    rows: 13,
    cols: 12,
    grid: [
      [null, "G", null, null, null, null, null, null, null, "G", null, null],
      ["M", "E", "D", "A", "I", "L", "L", "E", null, "I", null, null],
      [null, "S", null, null, "G", null, null, null, null, "R", null, null],
      ["S", "C", "H", "W", "E", "I", "N", null, null, "A", null, "B"],
      [null, "H", null, null, "L", null, null, null, null, "F", null, "I"],
      [null, "E", null, "K", "A", "R", "T", "O", "F", "F", "E", "L"],
      [null, "N", null, null, null, null, null, null, null, "E", null, "D"],
      [null, "K", "R", "A", "N", "K", "E", "N", "H", "A", "U", "S"],
      [null, null, null, null, null, null, null, null, null, null, null, "C"],
      [null, null, null, "K", "N", "O", "B", "L", "A", "U", "C", "H"],
      [null, null, null, null, null, null, null, null, null, null, null, "I"],
      [null, null, null, null, null, "F", "E", "N", "S", "T", "E", "R"],
      [null, null, null, null, null, null, null, null, null, null, null, "M"],
    ],
    entries: [
      { number: 1, dir: "down", row: 0, col: 1, answer: "GESCHENK", clue: "Wird zum Geburtstag überreicht" },
      { number: 2, dir: "down", row: 0, col: 9, answer: "GIRAFFE", clue: "Tier mit dem längsten Hals" },
      { number: 3, dir: "across", row: 1, col: 0, answer: "MEDAILLE", clue: "Auszeichnung für Sportler:innen" },
      { number: 4, dir: "down", row: 1, col: 4, answer: "IGEL", clue: "Stacheliges Gartentier" },
      { number: 5, dir: "across", row: 3, col: 0, answer: "SCHWEIN", clue: "Rosa Hoftier, Symbol für Glück" },
      { number: 6, dir: "down", row: 3, col: 11, answer: "BILDSCHIRM", clue: "Zeigt Inhalte am Computer an" },
      { number: 7, dir: "across", row: 5, col: 3, answer: "KARTOFFEL", clue: "Knolle, wird gekocht oder frittiert" },
      { number: 8, dir: "across", row: 7, col: 1, answer: "KRANKENHAUS", clue: "Ort zur medizinischen Behandlung" },
      { number: 9, dir: "across", row: 9, col: 3, answer: "KNOBLAUCH", clue: "Würzige Knolle mit starkem Geruch" },
      { number: 10, dir: "across", row: 11, col: 5, answer: "FENSTER", clue: "Durchsichtige Öffnung in der Wand" },
    ],
  },
];
