/**
 * Content-Registry für alle Spiele/Tests.
 *
 * Bewusst als Daten-Array statt hartcodierter Seiten: neue Rätsel/Quiz/Tests
 * sollen sich später ohne Code-Änderung einpflegen lassen (siehe Briefing
 * Abschnitt 7). Diese Datei ist der Übergangszustand vor der echten
 * Datenbank-Anbindung — die Struktur (Felder, ProductLevel) bleibt beim
 * Umzug nach Supabase gleich.
 */

export type ProductLevel = "daily-free" | "weekly-freemium" | "subscriber-only";

/** Die drei Spielarten aus dem Base44-Vorbild -- steuert Kategorie-Farbe & Icon. */
export type GameType = "quiz" | "puzzle" | "psych";

export interface GameModule {
  slug: string;
  title: string;
  teaser: string;
  emoji: string;
  category: string;
  level: ProductLevel;
  estMinutes: number;
  type: GameType;
  isPremium: boolean;
  sortOrder: number;
  /** Nur für type "puzzle"/"psych": welche Spielmechanik gerendert wird.
   * "psych-result"/"psych-compat" sind die beiden handgeschriebenen
   * Ur-Tests (Einzelkauf); "psych-generic" sind die content-getriebenen
   * Tests aus content/psychTests.ts (Plus-Freischaltung statt Einzelkauf). */
  variant?: "sliding" | "whoami" | "crossword" | "psych-result" | "psych-compat" | "psych-generic";
  /** Nur für die Sliding-Puzzle-Variante: Rastergröße. */
  difficulty?: "easy" | "medium" | "hard";
  /** false = taucht nicht in /kategorie/[type] auf (z.B. der tägliche Anker,
   * der schon auf der Startseite prominent verlinkt ist). Default true. */
  inCategoryBrowser?: boolean;
}

export const levelMeta: Record<
  ProductLevel,
  { label: string; description: string; badgeClass: string }
> = {
  "daily-free": {
    label: "Täglicher Gratis-Anker",
    description: "Jeden Tag neu, komplett kostenlos, kein Zufallselement mit Vermögenswert.",
    badgeClass: "bg-green-soft text-green-dark",
  },
  "weekly-freemium": {
    label: "Wöchentlicher Selbst-Test",
    description: "Grobes Ergebnis immer gratis sichtbar — Themen-Analyse optional als Einmalkauf.",
    badgeClass: "bg-primary-soft text-primary-dark",
  },
  "subscriber-only": {
    label: "Power-User-Bereich",
    description: "Im Mini-Abo enthalten: alle Tiefenauswertungen, Archiv, werbefrei.",
    badgeClass: "bg-gold-soft text-gold-dark",
  },
};

export const games: GameModule[] = [
  // Ebene 1 – täglicher Gratis-Anker
  {
    slug: "tages-raetsel",
    title: "Tagespuzzle",
    teaser: "Das tägliche Logikrätsel zum Knobeln.",
    emoji: "🧩",
    category: "Logik",
    level: "daily-free",
    estMinutes: 3,
    type: "puzzle",
    isPremium: false,
    sortOrder: 1,
  },
  {
    slug: "tages-mini-quiz",
    title: "Tages-Mini-Quiz",
    teaser: "Drei Fragen quer durchs Allgemeinwissen — für den Login-Streak.",
    emoji: "⚡",
    category: "Allgemeinwissen",
    level: "daily-free",
    estMinutes: 2,
    type: "quiz",
    isPremium: false,
    sortOrder: 2,
    inCategoryBrowser: false,
  },

  // Puzzle-Kategorie -- Reihenfolge 1:1 wie im Base44-Vorbild
  {
    slug: "wer-bin-ich",
    title: "Wer bin ich?",
    teaser: "Errate eine Person, einen Ort oder ein Werk anhand von sieben Hinweisen.",
    emoji: "🔎",
    category: "Rätsel",
    level: "weekly-freemium",
    estMinutes: 3,
    type: "puzzle",
    isPremium: false,
    sortOrder: 10,
  },
  {
    slug: "schiebepuzzle-leicht",
    title: "Schiebepuzzle Leicht",
    teaser: "Ein 3×3-Bildpuzzle — schiebe die Kacheln mit der Maus an die richtige Stelle.",
    emoji: "🧩",
    category: "Logik",
    level: "weekly-freemium",
    estMinutes: 2,
    type: "puzzle",
    variant: "sliding",
    difficulty: "easy",
    isPremium: false,
    sortOrder: 11,
  },
  {
    slug: "schiebepuzzle-mittel",
    title: "Schiebepuzzle Mittel",
    teaser: "Das 4×4-Bildpuzzle — mehr Kacheln, mehr Knobelei.",
    emoji: "🧩",
    category: "Logik",
    level: "weekly-freemium",
    estMinutes: 4,
    type: "puzzle",
    variant: "sliding",
    difficulty: "medium",
    isPremium: false,
    sortOrder: 12,
  },
  {
    slug: "schiebepuzzle-schwer",
    title: "Schiebepuzzle Schwer",
    teaser: "5×5 Kacheln für echte Puzzler — das volle Bild aus 24 Teilen zusammenschieben.",
    emoji: "🧩",
    category: "Logik",
    level: "subscriber-only",
    estMinutes: 7,
    type: "puzzle",
    variant: "sliding",
    difficulty: "hard",
    isPremium: true,
    sortOrder: 14,
  },
  {
    slug: "kreuzwortraetsel-leicht",
    title: "Kreuzworträtsel Leicht",
    teaser: "Klassisches Kreuzworträtsel, überschaubare Größe -- waagerecht und senkrecht, ganz digital.",
    emoji: "📝",
    category: "Wörter",
    level: "weekly-freemium",
    estMinutes: 6,
    type: "puzzle",
    variant: "crossword",
    difficulty: "easy",
    isPremium: false,
    sortOrder: 15,
  },
  {
    slug: "kreuzwortraetsel-mittel",
    title: "Kreuzworträtsel Mittel",
    teaser: "Größeres Gitter, rund 15 Begriffe -- exklusiv für Plus-Mitglieder.",
    emoji: "📝",
    category: "Wörter",
    level: "subscriber-only",
    estMinutes: 9,
    type: "puzzle",
    variant: "crossword",
    difficulty: "medium",
    isPremium: true,
    sortOrder: 16,
  },
  {
    slug: "kreuzwortraetsel-schwer",
    title: "Kreuzworträtsel Schwer",
    teaser: "Das große Rätsel mit mindestens 25 Begriffen -- exklusiv für Plus-Mitglieder.",
    emoji: "📝",
    category: "Wörter",
    level: "subscriber-only",
    estMinutes: 15,
    type: "puzzle",
    variant: "crossword",
    difficulty: "hard",
    isPremium: true,
    sortOrder: 17,
  },
  // "Wer bin ich?" -- drei Schwierigkeitsstufen. Eigene, unsichtbare
  // GameModule-Einträge (inCategoryBrowser: false, hoher sortOrder), damit
  // sie nicht als weitere Kacheln im Grid auftauchen, sondern nur über
  // /quiz/wer-bin-ich (die 3-Kacheln-Auswahlseite) erreichbar sind.
  {
    slug: "wer-bin-ich-leicht",
    title: "Wer bin ich? · Leicht",
    teaser: "Ein neues Rätsel pro Tag -- kostenlos.",
    emoji: "🔎",
    category: "Rätsel",
    level: "daily-free",
    estMinutes: 3,
    type: "puzzle",
    variant: "whoami",
    difficulty: "easy",
    isPremium: false,
    sortOrder: 900,
    inCategoryBrowser: false,
  },
  {
    slug: "wer-bin-ich-mittel",
    title: "Wer bin ich? · Mittel",
    teaser: "Mehrere Rätsel pro Tag, etwas kniffliger -- für Plus-Mitglieder.",
    emoji: "🔎",
    category: "Rätsel",
    level: "subscriber-only",
    estMinutes: 3,
    type: "puzzle",
    variant: "whoami",
    difficulty: "medium",
    isPremium: true,
    sortOrder: 901,
    inCategoryBrowser: false,
  },
  {
    slug: "wer-bin-ich-schwer",
    title: "Wer bin ich? · Schwer",
    teaser: "Die kniffligsten Rätsel, mehrere pro Tag -- für Plus-Mitglieder.",
    emoji: "🔎",
    category: "Rätsel",
    level: "subscriber-only",
    estMinutes: 4,
    type: "puzzle",
    variant: "whoami",
    difficulty: "hard",
    isPremium: true,
    sortOrder: 902,
    inCategoryBrowser: false,
  },

  // Quiz-Kategorie -- Reihenfolge 1:1 wie im Base44-Vorbild
  {
    slug: "filmzitate",
    title: "Filmzitate",
    teaser: "Erkenne den Film am berühmten Zitat.",
    emoji: "🎬",
    category: "Unterhaltung",
    level: "weekly-freemium",
    estMinutes: 2,
    type: "quiz",
    isPremium: false,
    sortOrder: 20,
  },
  {
    slug: "weltereignisse-xxl",
    title: "Weltereignisse XXL",
    teaser: "Erweiterte Runde mit über 30 Fragen weltweit.",
    emoji: "🌐",
    category: "Wissen",
    level: "subscriber-only",
    estMinutes: 8,
    type: "quiz",
    isPremium: true,
    sortOrder: 21,
  },
  {
    slug: "geschichte",
    title: "Geschichte",
    teaser: "Von Antike bis Mauerfall — reise durch die Menschheitsgeschichte.",
    emoji: "📜",
    category: "Wissen",
    level: "weekly-freemium",
    estMinutes: 3,
    type: "quiz",
    isPremium: false,
    sortOrder: 22,
  },
  {
    slug: "geographie",
    title: "Geographie",
    teaser: "Hauptstädte, Flüsse, Kontinente — dein Weltwissen auf dem Prüfstand.",
    emoji: "🌍",
    category: "Wissen",
    level: "weekly-freemium",
    estMinutes: 3,
    type: "quiz",
    isPremium: false,
    sortOrder: 23,
  },
  {
    slug: "zeitgeschehen",
    title: "Zeitgeschehen",
    teaser: "Was bewegt die Welt aktuell? Nachrichten & Trends der letzten Jahre.",
    emoji: "🧠",
    category: "Wissen",
    level: "weekly-freemium",
    estMinutes: 4,
    type: "quiz",
    isPremium: false,
    sortOrder: 24,
  },
  {
    slug: "wissenschaft-natur",
    title: "Wissenschaft & Natur",
    teaser: "Physik, Chemie, Biologie — vermesse die Naturgesetze.",
    emoji: "🧪",
    category: "Wissen",
    level: "weekly-freemium",
    estMinutes: 3,
    type: "quiz",
    isPremium: false,
    sortOrder: 25,
  },
  {
    slug: "sport",
    title: "Sport",
    teaser: "Rekorde, Regeln, Legenden — für Fußball- und Olympia-Fans.",
    emoji: "🏆",
    category: "Unterhaltung",
    level: "weekly-freemium",
    estMinutes: 3,
    type: "quiz",
    isPremium: false,
    sortOrder: 26,
  },
  {
    slug: "musik",
    title: "Musik",
    teaser: "Von Beethoven bis Beats — Noten, Stars und Instrumente.",
    emoji: "🎵",
    category: "Unterhaltung",
    level: "weekly-freemium",
    estMinutes: 3,
    type: "quiz",
    isPremium: false,
    sortOrder: 27,
  },
  {
    slug: "literatur-sprache",
    title: "Literatur & Sprache",
    teaser: "Autoren, Bestseller und Sprachkuriositäten.",
    emoji: "📖",
    category: "Wissen",
    level: "weekly-freemium",
    estMinutes: 3,
    type: "quiz",
    isPremium: false,
    sortOrder: 28,
  },
  {
    slug: "essen-trinken",
    title: "Essen & Trinken",
    teaser: "Zutaten, Herkunft und Köstlichkeiten rund um den Globus.",
    emoji: "🍽️",
    category: "Unterhaltung",
    level: "weekly-freemium",
    estMinutes: 3,
    type: "quiz",
    isPremium: false,
    sortOrder: 29,
  },
  {
    slug: "technik-digital",
    title: "Technik & Digital",
    teaser: "Bytes, KI und Gadgets — für Technik-Affine.",
    emoji: "💻",
    category: "Wissen",
    level: "weekly-freemium",
    estMinutes: 3,
    type: "quiz",
    isPremium: false,
    sortOrder: 30,
  },
  {
    slug: "gemischt",
    title: "Gemischt",
    teaser: "Ein bunter Mix aus 30 Fragen über alle Themen — für echte Allrounder. Plus-Runde.",
    emoji: "🧠",
    category: "Wissen",
    level: "subscriber-only",
    estMinutes: 6,
    type: "quiz",
    isPremium: true,
    sortOrder: 31,
  },

  // Selbsttests -- unverändert, noch nicht neu abgeglichen
  {
    slug: "beziehungstyp",
    title: "Dein Beziehungstyp",
    teaser: "Wie tickst du in Beziehungen wirklich? Unterhaltsame Tendenz, keine Diagnose.",
    emoji: "💬",
    category: "Persönlichkeit",
    level: "weekly-freemium",
    estMinutes: 4,
    type: "psych",
    variant: "psych-result",
    isPremium: false,
    sortOrder: 40,
  },
  {
    slug: "freundes-kompatibilitaet",
    title: "Freundes-Kompatibilität",
    teaser: "Macht den Test, teilt den Link, vergleicht eure Ergebnisse.",
    emoji: "🤝",
    category: "Kompatibilität",
    level: "weekly-freemium",
    estMinutes: 3,
    type: "psych",
    variant: "psych-compat",
    isPremium: false,
    sortOrder: 41,
  },

  // 24 weitere Selbsttests, content-getrieben über PsychResultTest +
  // content/psychTests.ts -- Ergebnis kurz immer sichtbar, die ausführliche
  // Analyse mit Plus. isPremium: false, weil der Test selbst frei bleibt
  // (nur die Tiefenauswertung ist Plus-exklusiv, wie bei Beziehungstyp).
  {
    slug: "kommunikationsstil",
    title: "Dein Kommunikationsstil",
    teaser: "Wie drückst du dich in Beziehungen wirklich aus? Unterhaltsame Tendenz, keine Diagnose.",
    emoji: "💭",
    category: "Persönlichkeit",
    level: "weekly-freemium",
    estMinutes: 4,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 42,
  },
  {
    slug: "eifersucht-test",
    title: "Wie eifersüchtig bist du wirklich?",
    teaser: "Ein ehrlicher, unterhaltsamer Blick auf deine eifersüchtige Seite.",
    emoji: "👀",
    category: "Persönlichkeit",
    level: "weekly-freemium",
    estMinutes: 2,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 43,
  },
  {
    slug: "freundschaftstyp",
    title: "Loyalist oder Freigeist?",
    teaser: "Dein Freundschaftstyp -- wie du Nähe und Freiheit unter Freund:innen balancierst.",
    emoji: "🫂",
    category: "Persönlichkeit",
    level: "weekly-freemium",
    estMinutes: 4,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 44,
  },
  {
    slug: "persoenlichkeitstyp",
    title: "Welcher Persönlichkeitstyp bist du?",
    teaser: "Die große Tiefenauswertung deiner Persönlichkeit -- ausführlich und ehrlich.",
    emoji: "🧭",
    category: "Persönlichkeit",
    level: "weekly-freemium",
    estMinutes: 7,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 45,
  },
  {
    slug: "optimist-oder-realist",
    title: "Optimist oder Realist?",
    teaser: "Siehst du das Glas halb voll oder rechnest du lieber mit dem Schlimmsten?",
    emoji: "🌤️",
    category: "Persönlichkeit",
    level: "weekly-freemium",
    estMinutes: 2,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 46,
  },
  {
    slug: "stress-typ",
    title: "Wie tickst du unter Stress?",
    teaser: "Kampf, Flucht oder cool bleiben -- dein Verhalten, wenn's eng wird.",
    emoji: "🌪️",
    category: "Persönlichkeit",
    level: "weekly-freemium",
    estMinutes: 4,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 47,
  },
  {
    slug: "introvertiert-oder-extrovertiert",
    title: "Introvertiert oder Extrovertiert?",
    teaser: "Dein Energie-Typ -- tankst du beim Alleinsein auf oder unter Menschen?",
    emoji: "🔋",
    category: "Persönlichkeit",
    level: "weekly-freemium",
    estMinutes: 4,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 48,
  },
  {
    slug: "empathie-test",
    title: "Wie empathisch bist du wirklich?",
    teaser: "Wie gut fühlst du dich in andere hinein? Ein ehrlicher Selbsttest.",
    emoji: "💗",
    category: "Persönlichkeit",
    level: "weekly-freemium",
    estMinutes: 4,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 49,
  },
  {
    slug: "chaos-typ-haushalt",
    title: "Welcher Chaos-Typ bist du im Haushalt?",
    teaser: "Aufgeräumt, kreatives Chaos oder irgendwo dazwischen?",
    emoji: "🧹",
    category: "Alltag",
    level: "weekly-freemium",
    estMinutes: 2,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 50,
  },
  {
    slug: "morgenmensch-oder-nachteule",
    title: "Morgenmensch oder Nachteule?",
    teaser: "Dein natürlicher Rhythmus -- und wie sehr er gegen den Alltag ankämpft.",
    emoji: "🌙",
    category: "Alltag",
    level: "weekly-freemium",
    estMinutes: 2,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 51,
  },
  {
    slug: "reisetyp",
    title: "Reisetyp: Planer oder Spontan?",
    teaser: "Excel-Tabelle oder Koffer packen und losfahren -- wie reist du wirklich?",
    emoji: "🧳",
    category: "Alltag",
    level: "weekly-freemium",
    estMinutes: 4,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 52,
  },
  {
    slug: "geldtyp",
    title: "Wie gehst du mit Geld um?",
    teaser: "Sparfuchs, Genießer oder Vogel-Strauß-Taktik -- dein Geld-Typ im Alltag.",
    emoji: "💶",
    category: "Alltag",
    level: "weekly-freemium",
    estMinutes: 4,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 53,
  },
  {
    slug: "minimalist-oder-sammler",
    title: "Minimalist oder Sammler?",
    teaser: "Dein Ordnungs-Level -- leerer Raum oder liebevolles Chaos?",
    emoji: "📦",
    category: "Alltag",
    level: "weekly-freemium",
    estMinutes: 2,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 54,
  },
  {
    slug: "arbeitstyp",
    title: "Welcher Arbeitstyp bist du?",
    teaser: "Wie du wirklich am liebsten arbeitest -- und was dich antreibt.",
    emoji: "💼",
    category: "Beruf",
    level: "weekly-freemium",
    estMinutes: 4,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 55,
  },
  {
    slug: "teamplayer-oder-einzelkaempfer",
    title: "Teamplayer oder Einzelkämpfer?",
    teaser: "Läufst du im Team oder solo zur Höchstform auf?",
    emoji: "🤾",
    category: "Beruf",
    level: "weekly-freemium",
    estMinutes: 2,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 56,
  },
  {
    slug: "fuehrungsstil",
    title: "Dein Führungsstil-Test",
    teaser: "Die große Analyse: wie du führst, entscheidest und dein Team mitnimmst.",
    emoji: "🧑‍✈️",
    category: "Beruf",
    level: "weekly-freemium",
    estMinutes: 7,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 57,
  },
  {
    slug: "nein-sagen-test",
    title: "Wie gut kannst du \"Nein\" sagen?",
    teaser: "Zwischen Gefallen-wollen und eigenen Grenzen -- wo stehst du?",
    emoji: "🙅",
    category: "Beruf",
    level: "weekly-freemium",
    estMinutes: 2,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 58,
  },
  {
    slug: "bauch-oder-kopf",
    title: "Bauchentscheider oder Kopfmensch?",
    teaser: "Triffst du Entscheidungen aus dem Bauch heraus oder mit der Tabelle?",
    emoji: "🧠",
    category: "Denken",
    level: "weekly-freemium",
    estMinutes: 4,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 59,
  },
  {
    slug: "konfliktstil",
    title: "Dein Konfliktstil-Test",
    teaser: "Die ausführliche Analyse: wie du in Streit und Meinungsverschiedenheiten agierst.",
    emoji: "⚡",
    category: "Denken",
    level: "weekly-freemium",
    estMinutes: 7,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 60,
  },
  {
    slug: "veraenderungstyp",
    title: "Wie gehst du mit Veränderungen um?",
    teaser: "Neue Situationen: Abenteuer oder Stressfaktor? Dein Umgang mit Wandel.",
    emoji: "🔄",
    category: "Denken",
    level: "weekly-freemium",
    estMinutes: 4,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 61,
  },
  {
    slug: "filmcharakter-test",
    title: "Welcher Filmcharakter bist du?",
    teaser: "Von Held bis Antiheld -- welcher Filmtyp steckt wirklich in dir?",
    emoji: "🎬",
    category: "Unterhaltung",
    level: "weekly-freemium",
    estMinutes: 4,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 62,
  },
  {
    slug: "jahrzehnt-test",
    title: "Welches Jahrzehnt passt zu dir?",
    teaser: "60er-Flair, 90er-Vibe oder doch ganz Gegenwart -- dein Lebensgefühl im Jahrzehnt-Check.",
    emoji: "📻",
    category: "Unterhaltung",
    level: "weekly-freemium",
    estMinutes: 2,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 63,
  },
  {
    slug: "serie-oder-buch",
    title: "Team Serie oder Team Buch?",
    teaser: "Bingewatchen oder Seiten umblättern -- und was das über dich verrät.",
    emoji: "📺",
    category: "Unterhaltung",
    level: "weekly-freemium",
    estMinutes: 2,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 64,
  },
  {
    slug: "fabelwesen-test",
    title: "Welches Fabelwesen steckt in dir?",
    teaser: "Drache, Fee, Phönix oder Einhorn -- dein mythisches Alter Ego.",
    emoji: "🐉",
    category: "Unterhaltung",
    level: "weekly-freemium",
    estMinutes: 2,
    type: "psych",
    variant: "psych-generic",
    isPremium: false,
    sortOrder: 65,
  },
];

export const gameTypeMeta: Record<GameType, { label: string; description: string }> = {
  quiz: {
    label: "Quiz",
    description: "Schnelle Wissensrunden — Allgemein, Filme, Weltwissen & mehr.",
  },
  puzzle: {
    label: "Puzzle",
    description: "Kurze Logik- und Bilderrätsel zum Knobeln zwischendurch.",
  },
  psych: {
    label: "Selbsttests",
    description: "Kurzweilige Persönlichkeitsspiele — Unterhaltung, keine Beratung.",
  },
};
